query awsEksClusterRuntimePickComponent($kubernetesVersion: String) {
  awsEksClusterRuntimePickComponent(input:{kubernetesVersion: $kubernetesVersion}) {
    component {
      id
      displayName
      kubernetesVersion
    }
    implicitConstraints {
      field
      value
    }
  }
}

