load("@prelude-si//:macros.bzl", "rust_library")

rust_library(
    name = "si-aws-config",
    deps = [
        "//lib/telemetry-rs:telemetry",

        "//third-party/rust:aws-config",
        "//third-party/rust:aws-sdk-sts",
        "//third-party/rust:remain",
        "//third-party/rust:thiserror",
        "//third-party/rust:tokio",
    ],
    srcs = glob([
        "src/**/*.rs",
    ]),
)
