query awsEksClusterRuntimeGetEntity($entityId: String) {
  awsEksClusterRuntimeGetEntity(input: { entityId: $entityId }) {
    entity {
      id
      naturalKey
      typeName
      name
      displayName
      description
      constraints {
        kubernetesVersion
      }
      implicitConstraints {
        field
        value
      }
      state
      kubernetesVersion
      awsStatus
    }
  }
}

