query awsEksClusterRuntimeListEntityEvents(
  $pageSize: Int, 
  $orderBy: String, 
  $orderByDirection: DataOrderByDirection, 
  $pageToken: String
  $scopeByTenantId: String,
) {
  awsEksClusterRuntimeListEntityEvents(input: {
    pageSize: $pageSize,
    orderBy: $orderBy,
    orderByDirection: $orderByDirection,
    pageToken: $pageToken,
    scopeByTenantId: $scopeByTenantId,
  }) {
    items {
      id
      actionName
      entity {
        id
        displayName
      }
      user {
        id
        displayName
      }
      createTime
      updatedTime
      finalized
      success
    }
    totalCount
    nextPageToken
  }
}

