[package]
name = "modat-cli"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"
publish = false

[[bin]]
name = "modat"
path = "src/main.rs"

[dependencies]
clap = { version = "3.1.12", features = ["derive", "color", "env"] }
color-eyre = { version = "0.6.1" }
modat-server = { path = "../../lib/modat-server" }
telemetry = { path = "../../lib/telemetry-rs", features = ["application"] }
tokio = { version = "1.12.0", features = ["full"] }
