[package]
name = "si-cyclone"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.2.5", features = ["ws"] }
clap = { version = "3.0.0-beta.4" }
color-eyre = "0.5.11"
hyper = { version = "0.14.13", features = ["http1", "runtime", "server"] }
opentelemetry = { version = "0.16.0", features = ["rt-tokio", "trace"] }
opentelemetry-otlp = "0.9.0"
opentelemetry-semantic-conventions = "0.8.0"
thiserror = "1.0"
tokio = { version = "1.12.0", features = ["full"] }
tower-http = { version = "0.1", features = ["trace"] }
tracing = "0.1"
tracing-opentelemetry = "0.15.0"
tracing-subscriber = "0.2.19"
