load("@prelude-si//:macros.bzl", "rust_library")

rust_library(
    name = "nats-dead-letter-queue",
    deps = [
        "//lib/si-data-nats:si-data-nats",
        "//lib/telemetry-rs:telemetry",
        "//third-party/rust:remain",
        "//third-party/rust:thiserror",
    ],
    srcs = glob([
        "src/**/*.rs",
    ]),
)
