load("@prelude-si//:macros.bzl", "rust_library")

rust_library(
    name = "telemetry-http",
    deps = [
        "//lib/telemetry-rs:telemetry",
        "//third-party/rust:hyper",
        "//third-party/rust:remain",
        "//third-party/rust:tower-http",
    ],
    srcs = glob(["src/**/*.rs"]),
)
