si-sdf:
  - components/si-sdf/**/*
si-registry:
  - components/si-registry/**/*
si-web-app:
  - components/si-web-app/**/*
si-pedant:
  - components/si-pedant/**/*
nats:
  - components/nats
couchbase:
  - components/couchbase
opentelemetry:
  - components/opentelemetry-collector
ci:
  - .github/**/*
