#
# Project infrastructure
#
A-ci:
  - changed-files:
    - any-glob-to-any-file:
      - .ci/**/*
      - .github/**/*
      - Makefile
      - ./**/Makefile
A-docs:
  - changed-files:
    - any-glob-to-any-file:
      - app/docs/**/*
      - docs/**/*

#
# System Initiative apps (i.e. webapps/ios apps/android apps)
#
A-web:
  - changed-files:
    - any-glob-to-any-file:
      - app/web/**/*
      - .prettierrc.js
      
A-auth:
  - changed-files:
    - any-glob-to-any-file:
      - app/docs/**/*
      - bin/auth-api/**/*

#
# System Initiative bins (i.e. services/programs/binaries)
#
A-cyclone:
  - changed-files:
    - any-glob-to-any-file:
      - bin/cyclone/**/*
      - lib/cyclone-client/**/*
      - lib/cyclone-core/**/*
      - lib/cyclone-server/**/*
      - .cargo/**/*
      - Cargo.lock
      - rust-toolchain
      - rustfmt.toml
A-sdf:
  - changed-files:
    - any-glob-to-any-file:
      - bin/sdf/**/*
      - lib/sdf-server/**/*
      - .cargo/**/*
      - Cargo.lock
      - rust-toolchain
      - rustfmt.toml
A-veritech:
  - changed-files:
    - any-glob-to-any-file:
      - bin/veritech/**/*
      - lib/veritech-client/**/*
      - lib/veritech-core/**/*
      - lib/veritech-server/**/*
      - .cargo/**/*
      - Cargo.lock
      - rust-toolchain
      - rustfmt.toml
A-pinga:
  - changed-files:
    - any-glob-to-any-file:
      - bin/pinga/**/*
      - lib/pinga-server/**/*
      - .cargo/**/*
      - Cargo.lock
      - rust-toolchain
      - rustfmt.toml
A-lang-js:
  - changed-files:
    - any-glob-to-any-file:
      - bin/lang-js/**/*
      - .prettierrc.js
A-module-index:
  - changed-files:
    - any-glob-to-any-file:
      - bin/module-index/**/*
      - .cargo/**/*
      - Cargo.lock
      - rust-toolchain
      - rustfmt.toml
A-si-discord-bot:
  - changed-files:
    - any-glob-to-any-file:
      - bin/si-discord-bot/**/*
      - .prettierrc.js
A-si:
  - changed-files:
    - any-glob-to-any-file:
      - bin/si/**/*
      - lib/si-cli/**/*
A-rebaser:
  - changed-files:
    - any-glob-to-any-file:
      - bin/rebaser/**/*
      - lib/rebaser-server/**/*
      - lib/rebaser-core/**/*
      - lib/rebaser-client/**/*
      - .cargo/**/*
      - Cargo.lock
      - rust-toolchain
      - rustfmt.toml
A-forklift:
  - changed-files:
    - any-glob-to-any-file:
      - bin/forklift/**/*
      - lib/forklift-server/**/*
      - lib/billing-events/**/*
      - lib/data-warehouse-stream-client/**/*
      - .cargo/**/*
      - Cargo.lock
      - rust-toolchain
      - rustfmt.toml
A-edda:
  - changed-files:
    - any-glob-to-any-file:
      - bin/edda/**/*
      - lib/edda-client/**/*
      - lib/edda-core/**/*
      - lib/edda-server/**/*
      - .cargo/**/*
      - Cargo.lock
      - rust-toolchain
      - rustfmt.toml

#
# System Initiative libs (i.e. crates/packages/libraries)
#
A-buck2-resources:
  - changed-files:
    - any-glob-to-any-file:
      - lib/A-buck2-resources/**/*
      - .cargo/**/*
      - Cargo.lock
      - rust-toolchain
      - rustfmt.toml
A-bytes-lines-codec:
  - changed-files:
    - any-glob-to-any-file:
      - lib/bytes-lines-codec/**/*
      - .cargo/**/*
      - Cargo.lock
      - rust-toolchain
      - rustfmt.toml
A-config-file:
  - changed-files:
    - any-glob-to-any-file:
      - lib/config-file/**/*
      - .cargo/**/*
      - Cargo.lock
      - rust-toolchain
      - rustfmt.toml
A-dal:
  - changed-files:
    - any-glob-to-any-file:
      - lib/dal/**/*
      - .cargo/**/*
      - Cargo.lock
      - rust-toolchain
      - rustfmt.toml
A-dal-test:
  - changed-files:
    - any-glob-to-any-file:
      - lib/dal-test/**/*
      - .cargo/**/*
      - Cargo.lock
      - rust-toolchain
      - rustfmt.toml
A-nats-subscriber:
  - changed-files:
    - any-glob-to-any-file:
      - lib/nats-subscriber/**/*
      - .cargo/**/*
      - Cargo.lock
      - rust-toolchain
      - rustfmt.toml
A-object-tree:
  - changed-files:
    - any-glob-to-any-file:
      - lib/object-tree/**/*
      - .cargo/**/*
      - Cargo.lock
      - rust-toolchain
      - rustfmt.toml
A-si-data-nats:
  - changed-files:
    - any-glob-to-any-file:
      - lib/si-data-nats/**/*
      - .cargo/**/*
      - Cargo.lock
      - rust-toolchain
      - rustfmt.toml
A-si-data-pg:
  - changed-files:
    - any-glob-to-any-file:
      - lib/si-data-pg/**/*
      - .cargo/**/*
      - Cargo.lock
      - rust-toolchain
      - rustfmt.toml
A-si-layer-cache:
  - changed-files:
    - any-glob-to-any-file:
      - lib/si-layer-cache/**/*
      - .cargo/**/*
      - Cargo.lock
      - rust-toolchain
      - rustfmt.toml
A-si-pkg:
  - changed-files:
    - any-glob-to-any-file:
      - lib/si-pkg/**/*
      - .cargo/**/*
      - Cargo.lock
      - rust-toolchain
      - rustfmt.toml
A-si-pool-noodle:
  - changed-files:
    - any-glob-to-any-file:
      - lib/si-pool-noodle/**/*
      - .cargo/**/*
      - Cargo.lock
      - rust-toolchain
      - rustfmt.toml
A-si-posthog-rs:
  - changed-files:
    - any-glob-to-any-file:
      - lib/si-posthog-rs/**/*
      - .cargo/**/*
      - Cargo.lock
      - rust-toolchain
      - rustfmt.toml
A-si-settings:
  - changed-files:
    - any-glob-to-any-file:
      - lib/si-settings/**/*
      - .cargo/**/*
      - Cargo.lock
      - rust-toolchain
      - rustfmt.toml
A-si-std:
  - changed-files:
    - any-glob-to-any-file:
      - lib/si-std/**/*
      - .cargo/**/*
      - Cargo.lock
      - rust-toolchain
      - rustfmt.toml
A-si-test-macros:
  - changed-files:
    - any-glob-to-any-file:
      - lib/si-test-macros/**/*
      - .cargo/**/*
      - Cargo.lock
      - rust-toolchain
      - rustfmt.toml
A-telemetry-application-rs:
  - changed-files:
    - any-glob-to-any-file:
      - lib/telemetry-application-rs/**/*
      - .cargo/**/*
      - Cargo.lock
      - rust-toolchain
      - rustfmt.toml
A-telemetry-rs:
  - changed-files:
    - any-glob-to-any-file:
      - lib/telemetry-rs/**/*
      - .cargo/**/*
      - Cargo.lock
      - rust-toolchain
      - rustfmt.toml

#
# Third-party development images
#
A-nats:
  - changed-files:
    - any-glob-to-any-file:
      - component/nats/**/*
A-otelcol:
  - changed-files:
    - any-glob-to-any-file:
      - component/otelcol/**/*
A-postgres:
  - changed-files:
    - any-glob-to-any-file:
      - component/postgres/**/*
A-skopeo:
  - changed-files:
    - any-glob-to-any-file:
      - component/skopeo/**/*
