si-ssh-key:
  - components/si-ssh-key/**/*
si-settings:
  - components/si-settings/**/*
si-data:
  - components/si-data/**/*
si-account:
  - components/si-account/**/*
si-graphql-api:
  - components/si-graphql-api/**/*
si-web-ui:
  - components/si-web-ui/**/*
infra:
  - components/infra/**/*
ci:
  - .github/**/*
