---
#
# Project infrastructure
#
A-ci:
  - .ci/**/*
  - .github/**/*
A-docs:
  - docs/**/*

#
# System Initiative apps (i.e. webapps/ios apps/android apps)
#
A-si-web:
  - components/si-web-app/**/*
  - .prettierrc.js

#
# System Initiative bins (i.e. services/programs/binaries)
#
A-cyclone:
  - bin/cyclone/**/*
  - lib/cyclone/**/*
  - .cargo/**/*
  - Cargo.lock
  - rust-toolchain
  - rustfmt.toml
A-sdf:
  - bin/sdf/**/*
  - lib/sdf/**/*
  - .cargo/**/*
  - Cargo.lock
  - rust-toolchain
  - rustfmt.toml
A-veritech:
  - bin/veritech/**/*
  - lib/veritech/**/*
  - .cargo/**/*
  - Cargo.lock
  - rust-toolchain
  - rustfmt.toml
A-lang-js:
  - bin/lang-js/**/*
  - .prettierrc.js

#
# System Initiative libs (i.e. crates/packages/libraries)
#
A-si-data:
  - lib/si-data/**/*
  - .cargo/**/*
  - Cargo.lock
  - rust-toolchain
  - rustfmt.toml
A-deadpool-cyclone:
  - lib/deadpool-cyclone/**/*
  - .cargo/**/*
  - Cargo.lock
  - rust-toolchain
  - rustfmt.toml
A-si-model:
  - lib/si-model/**/*
  - .cargo/**/*
  - Cargo.lock
  - rust-toolchain
  - rustfmt.toml
A-si-settings:
  - lib/si-settings/**/*
  - .cargo/**/*
  - Cargo.lock
  - rust-toolchain
  - rustfmt.toml

#
# Third-party development images
#
A-nats:
  - component/nats/**/*
A-otelcol:
  - component/otelcol/**/*
A-postgres:
  - component/postgres/**/*
A-skopeo:
  - component/skopeo/**/*
