[build]
# base = "components/si-web-app"
command = "make build//components/si-registry build//components/si-web-app"
publish = "components/si-web-app/dist"

[build.environment]
NODE_VERSION = "14"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
