# Get help on options with `rustfmt --help=config`
# Please keep these in alphabetical order.
edition = "2024"
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "Vertical"
newline_style = "Unix"
style_edition = "2024"
