---
version: "3"
services:
  postgres:
    build: ../../components/postgres
    ports:
      - "5432:5432"
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
  otelcol:
    build:
      context: ../../components/otelcol
      args:
        VERSION: 0.29.0
        CONFIG: otel-config.yaml
    environment:
      HONEYCOMB_TOKEN:
      HONEYCOMB_DATASET:
    ports:
      - "4317:4317"
      - "55679:55679"
  veritech:
    build:
      context: ../..
      dockerfile: components/si-veritech/Dockerfile
    ports:
      - "5157:5157"
    privileged: true
  sdf:
    build:
      context: ../..
      dockerfile: components/si-sdf/Dockerfile
    environment:
      SI_PG__HOSTNAME: postgres
      SI_NATS__URL: nats
      SI_VERITECH__WS_URL: ws://veritech:5157
      SI_VERITECH__HTTP_URL: http://veritech:5157
      SI_EVENT_LOG_FS__ROOT: /tmp/event-log-fs
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otelcol:4317
    ports:
      - "5156:5156"
    depends_on:
      - postgres
      - nats
      - otelcol
      - veritech
  web:
    build:
      context: ../..
      dockerfile: components/si-web-app/Dockerfile
      args:
        VUE_APP_SDF_BASE_HTTP_URL: http://app.systeminit.com/api
        VUE_APP_SDF_BASE_WS_URL: ws://app.systeminit.com/api/updates
    ports:
      - "8080:80"
