load("@prelude-si//:macros.bzl", "rust_library")

rust_library(
    name = "acceptable-tests",
    deps = [
        "//lib/acceptable:acceptable",
        "//third-party/rust:serde",
    ],
    srcs = glob([
        "src/**/*.rs",
    ]),
)
