load("@prelude//tests:test_toolchain.bzl", "noop_test_toolchain")
load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")
load(
    "@prelude//toolchains:python.bzl",
    "system_python_bootstrap_toolchain",
    "system_python_toolchain",
)
load(
    "@prelude//toolchains:remote_test_execution.bzl",
    "remote_test_execution_toolchain",
)
load("@prelude-si//artifact:toolchain.bzl", "artifact_toolchain")
load("@prelude-si//build_context:toolchain.bzl", "build_context_toolchain")
load("@prelude-si//deno:toolchain.bzl", "deno_toolchain")
load("@prelude-si//docker:toolchain.bzl", "docker_toolchain")
load("@prelude-si//e2e:toolchain.bzl", "e2e_toolchain")
load("@prelude-si//git:toolchain.bzl", "git_toolchain")
load("@prelude-si//nix:toolchain.bzl", "nix_toolchain")
load("@prelude-si//pnpm:toolchain.bzl", "pnpm_toolchain")
load("@prelude-si//python:toolchain.bzl", "si_python_toolchain")
load("@prelude-si//rootfs:toolchain.bzl", "rootfs_toolchain")
load("@prelude-si//rust:toolchain.bzl", "si_rust_toolchain")
load("@prelude-si//shell:toolchain.bzl", "shell_toolchain")
load(":toolchain.bzl", "toolchain_alias")
load(":rust_toolchain.bzl", "nix_rust_toolchain")

sh_binary(
    name = "rustc_wrapper",
    main = "rustc_wrapper.sh",
    visibility = ["PUBLIC"],
)

nix_rust_toolchain(
    name = "rust_release",
    default_edition = "2024",
    clippy_toml = "root//:clippy.toml",
    visibility = ["PUBLIC"],
    rustc_path = read_root_config("toolchains", "rust.rustc"),
    cargo_path = read_root_config("toolchains", "rust.cargo"),
    clippy_path = read_root_config("toolchains", "rust.clippy"),
    rustfmt_path = read_root_config("toolchains", "rust.rustfmt"),
    c_compiler = read_root_config("toolchains", "c.compiler"),
    cxx_compiler = read_root_config("toolchains", "cxx.compiler"),
    rustc_flags = [
        "-Copt-level=3",
        "-Cdebuginfo=line-tables-only",
        "-Cstrip=none",
        "-Cdebug-assertions=false",
        "-Coverflow-checks=false",
        "-Clto=false",
        "-Ccodegen-units=16",
        "-Clink-arg=-fuse-ld=",
        "-Clinker=" + read_root_config("toolchains", "c.compiler"),
    ],
)

nix_rust_toolchain(
    name = "rust_debug",
    default_edition = "2024",
    clippy_toml = "root//:clippy.toml",
    visibility = ["PUBLIC"],
    rustc_path = read_root_config("toolchains", "rust.rustc"),
    cargo_path = read_root_config("toolchains", "rust.cargo"),
    clippy_path = read_root_config("toolchains", "rust.clippy"),
    rustfmt_path = read_root_config("toolchains", "rust.rustfmt"),
    c_compiler = read_root_config("toolchains", "c.compiler"),
    cxx_compiler = read_root_config("toolchains", "cxx.compiler"),
    rustc_flags = [
        "-Copt-level=3",
        "-Cdebuginfo=line-tables-only",
        "-Cstrip=none",
        "-Cdebug-assertions=false",
        "-Coverflow-checks=false",
        "-Clto=false",
        "-Ccodegen-units=16",
        "-Clink-arg=-fuse-ld=",
        "-Clinker=" + read_root_config("toolchains", "c.compiler"),
    ],
)

remote_test_execution_toolchain(
    name = "remote_test_execution",
    visibility = ["PUBLIC"],
)

noop_test_toolchain(
    name = "test",
    visibility = ["PUBLIC"],
)

system_cxx_toolchain(
    name = "cxx",
    compiler = read_root_config("toolchains", "c.compiler"),
    cxx_compiler = read_root_config("toolchains", "cxx.compiler"),
    linker = read_root_config("toolchains", "cxx.linker"),
    visibility = ["PUBLIC"],
)

system_genrule_toolchain(
    name = "genrule",
    visibility = ["PUBLIC"],
)

system_python_toolchain(
    name = "python",
    interpreter = read_root_config("toolchains", "python"),
    visibility = ["PUBLIC"],
)

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    interpreter = read_root_config("toolchains", "python"),
    visibility = ["PUBLIC"],
)

toolchain_alias(
    name = "rust",
    actual = select({
        "root//config:build_debug": ":rust_debug",
        "root//config:build_release": ":rust_release",
    }),
    visibility = ["PUBLIC"],
)

build_context_toolchain(
    name = "build_context",
    visibility = ["PUBLIC"],
)

deno_toolchain(
    name = "deno",
    deno_bin = read_root_config("toolchains", "deno"),
    visibility = ["PUBLIC"],
)

docker_toolchain(
    name = "docker",
    visibility = ["PUBLIC"],
)

e2e_toolchain(
    name = "e2e",
    visibility = ["PUBLIC"],
)

artifact_toolchain(
    name = "artifact",
    visibility = ["PUBLIC"],
)

git_toolchain(
    name = "git",
    visibility = ["PUBLIC"],
)

nix_toolchain(
    name = "nix",
    visibility = ["PUBLIC"],
)

pnpm_toolchain(
    name = "pnpm",
    editorconfig = "root//:.editorconfig",
    pnpm_bin = read_root_config("toolchains", "pnpm"),
    visibility = ["PUBLIC"],
)

rootfs_toolchain(
    name = "rootfs",
    visibility = ["PUBLIC"],
)

si_python_toolchain(
    name = "si_python",
    visibility = ["PUBLIC"],
)

si_rust_toolchain(
    name = "si_rust",
    rustfmt_toml = "root//:rustfmt.toml",
    visibility = ["PUBLIC"],
)

shell_toolchain(
    name = "shell",
    editorconfig = "root//:.editorconfig",
    visibility = ["PUBLIC"],
)
