load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")
load(
    "@prelude//toolchains:python.bzl",
    "system_python_bootstrap_toolchain",
    "system_python_toolchain",
)
load("@prelude//toolchains:remote_test_execution.bzl", "remote_test_execution_toolchain")
load("@prelude//toolchains:rust.bzl", "system_rust_toolchain")
load("@prelude-si//build_context:toolchain.bzl", "build_context_toolchain")
load("@prelude-si//docker:toolchain.bzl", "docker_toolchain")
load("@prelude-si//artifact:toolchain.bzl", "artifact_toolchain")
load("@prelude-si//git:toolchain.bzl", "git_toolchain")
load("@prelude-si//nix:toolchain.bzl", "nix_toolchain")
load("@prelude-si//pnpm:toolchain.bzl", "pnpm_toolchain")
load("@prelude-si//python:toolchain.bzl", "si_python_toolchain")
load("@prelude-si//rust:toolchain.bzl", "si_rust_toolchain")
load("@prelude-si//shell:toolchain.bzl", "shell_toolchain")
load("@prelude-si//rootfs:toolchain.bzl", "rootfs_toolchain")

remote_test_execution_toolchain(
    name = "remote_test_execution",
    visibility = ["PUBLIC"],
)

system_cxx_toolchain(
    name = "cxx",
    visibility = ["PUBLIC"],
)

system_genrule_toolchain(
    name = "genrule",
    visibility = ["PUBLIC"],
)

system_python_toolchain(
    name = "python",
    visibility = ["PUBLIC"],
)

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)

system_rust_toolchain(
    name = "rust",
    default_edition = "2021",
    clippy_toml = "root//:clippy.toml",
    visibility = ["PUBLIC"],
)

build_context_toolchain(
    name = "build_context",
    visibility = ["PUBLIC"],
)

docker_toolchain(
    name = "docker",
    visibility = ["PUBLIC"],
)

artifact_toolchain(
    name = "artifact",
    visibility = ["PUBLIC"],
)

git_toolchain(
    name = "git",
    visibility = ["PUBLIC"],
)

nix_toolchain(
    name = "nix",
    visibility = ["PUBLIC"],
)

pnpm_toolchain(
    name = "pnpm",
    editorconfig = "root//:.editorconfig",
    visibility = ["PUBLIC"],
)

si_python_toolchain(
    name = "si_python",
    visibility = ["PUBLIC"],
)

si_rust_toolchain(
    name = "si_rust",
    rustfmt_toml = "root//:rustfmt.toml",
    visibility = ["PUBLIC"],
)

shell_toolchain(
    name = "shell",
    editorconfig = "root//:.editorconfig",
    visibility = ["PUBLIC"],
)

rootfs_toolchain(
    name = "rootfs",
    visibility = ["PUBLIC"],
)
