load("@prelude-si//:macros.bzl", "rust_library")

rust_library(
    name = "innit-client",
    deps = [
        "//lib/innit-core:innit-core",
        "//lib/telemetry-rs:telemetry",

        "//third-party/rust:remain",
        "//third-party/rust:reqwest",
        "//third-party/rust:serde_json",
        "//third-party/rust:thiserror",
        "//third-party/rust:url",
    ],
    srcs = glob([
        "src/**/*.rs",
    ]),
)
