include ../../mk/base.mk
include ../../mk/rust.mk

.DEFAULT_GOAL := build
#CONTAINER_NAME := sdf
#IMG := systeminit/sdf
WATCH_PATHS := . \
	../../lib/config-file \
	../../lib/si-data \
	../../lib/si-settings \
	../../lib/telemetry-rs
