#!/usr/bin/env python3
"""
Generates TypeScript version constants from git metadata JSON.
"""
import argparse
import json
import sys
from typing import Any, Dict


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "git_metadata_json",
        help="Path to git metadata JSON file",
    )
    parser.add_argument(
        "output",
        help="Output TypeScript file path",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    with open(args.git_metadata_json) as f:
        data = json.load(f)

    ts_content = generate_typescript(data)

    with open(args.output, "w") as f:
        f.write(ts_content)

    return 0


def generate_typescript(data: Dict[str, Any]) -> str:
    """Generate TypeScript version constants from git metadata."""
    return f'''// Generated by Buck2 from git metadata
// DO NOT EDIT - changes will be overwritten

/** Abbreviated commit hash (typically 8 characters) */
export const ABBREVIATED_COMMIT_HASH = "{data['abbreviated_commit_hash']}";
/** Git branch name */
export const BRANCH = "{data['branch']}";
/** Calendar version in `YYYYMMDD.hhmmss.0` format (e.g., "20241127.123456.0") */
export const CAL_VER = "{data['cal_ver']}";
/** Commit date in strict ISO 8601 format (e.g., "2024-11-27T12:34:56Z") */
export const COMMITTER_DATE_ISO8601 = "{data['committer_date_strict_iso8601']}";
/** Commit date as Unix timestamp (seconds since epoch) */
export const COMMITTER_DATE_TIMESTAMP = {data['committer_date_timestamp']};
/** Full 40-character commit SHA-1 hash */
export const COMMIT_HASH = "{data['commit_hash']}";
/** Whether the working tree had uncommitted changes at build time */
export const IS_DIRTY = {str(data['is_dirty']).lower()};
/**
 * Canonical version string combining calendar version and commit hash (e.g.,
 * "20241127.123456.0-sha.a1b2c3d")
 */
export const VERSION = "{data['canonical_version']}";
'''


if __name__ == "__main__":
    sys.exit(main())
