load("@prelude-si//:macros.bzl", "rust_library")

rust_library(
    name = "object-tree",
    deps = [
        "//lib/si-hash:si-hash",
        "//third-party/rust:petgraph",
        "//third-party/rust:remain",
        "//third-party/rust:serde",
        "//third-party/rust:serde_json",
        "//third-party/rust:strum",
        "//third-party/rust:tar",
        "//third-party/rust:thiserror",
    ],
    srcs = glob(["src/**/*.rs"]),
)
