load("@prelude-si//:macros.bzl", "rust_library")

rust_library(
    name = "gobbler-client",
    deps = [
        "//lib/gobbler-server:gobbler-server",
        "//lib/si-rabbitmq:si-rabbitmq",
        "//lib/telemetry-rs:telemetry",
        "//third-party/rust:remain",
        "//third-party/rust:serde",
        "//third-party/rust:serde_json",
        "//third-party/rust:thiserror",
        "//third-party/rust:ulid",
    ],
    srcs = glob([
        "src/**/*.rs",
    ]),
)
