[package]
name = "si-data"
version = "0.1.0"
authors = ["Adam Jacob <adam@systeminit.com>"]
edition = "2018"

[[bin]]
name = "si-keygen"
path = "src/bin/keygen.rs"
edition = "2018"

[dependencies]
anyhow = "1.0"
uuid = { version = "0.7", features = [ "serde", "v4" ] }
futures = { version = "0.3", default-features = false, features = ["alloc"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
couchbase = { path = "../../vendor/couchbase-rs/couchbase" }
tracing = "0.1.10"
tracing-futures = { version = "0.1.1", features = ["tokio", "std-future"] }
sodiumoxide = "0.2"
serde_cbor = "0.10"
base64 = "0.10.1"
names = "0.11"
prost = "0.6"
prost-derive = "0.6"
bytes = "0.5"
thiserror = "1.0"
tokio = { version = "0.2", features = [ "full" ] } 
toml = "0.5"

# Internal Dependencies
si-settings = { path = "../si-settings" }

[build-dependencies]
prost-build = "0.6"

[dev-dependencies]
ureq = "0.11" 
lazy_static = "1.4"
tracing-subscriber = "0.1.6"

