# Set args to "True" if we want to allow positional arguments
config.define_string_list("to-run", args = True)
config.define_bool("standard-rustc-build-mode")
config.define_bool("debug-rustc-build-mode")
config.define_bool("debug-no-rebaser-rustc-build-mode")

cfg = config.parse()

# Define groups of services
groups = {
    "platform": [
        "grafana",
        "jaeger",
        "nats",
        "otelcol",
        "db",
        "db-test",
        "postgres",
        "postgres-test",
        "localstack",
    ],
    "backend": [
        "pinga",
        "veritech",
        "sdf",
        "module-index",
        "rebaser",
    ],
    "frontend": [
        "web",
    ],
}

# Add "all" group as a sorted set of all services
_all = {}
for group_values in groups.values():
    for value in group_values:
        _all.update({value: True})
groups.update({"all": sorted(_all.keys())})

# Parse the CLI args to enable group names and/or individual service names
enabled_resources = []
for arg in cfg.get("to-run", []):
    if arg in groups:
        enabled_resources += groups[arg]
    else:
        enabled_resources.append(arg)
config.set_enabled_resources(enabled_resources)

# Parse the CLI args to get the rustc build mode or default to release
standard_rustc_build_mode = cfg.get('standard-rustc-build-mode', False)
debug_rustc_build_mode = cfg.get('debug-rustc-build-mode', False)
debug_no_rebaser_rustc_build_mode = cfg.get('debug-no-rebaser-rustc-build-mode', False)
rustc_build_mode = 'release'

# TODO(nick): the bzl logic for writing arguments out does not know how
# to group string ("config.define_string") arguments with the argument
# call (i.e. it thinks "--foo bar" is one argument rather than having
# argument "--foo" be passed value "bar"). Thus, we use two booleans to
# get around this. If we get both, greedily choose the standard mode.
if standard_rustc_build_mode:
    rustc_build_mode = 'standard'
elif debug_rustc_build_mode:
    rustc_build_mode = 'debug'
elif debug_no_rebaser_rustc_build_mode:
    rustc_build_mode = 'debug'

# Default trigger mode to manual so that (importantly) backend services don't rebuild/restart
# automatically. This is opt-in in the Tilt UI in the `Mode` column
trigger_mode = TRIGGER_MODE_MANUAL

def _buck2_dep_inputs(target):
    cmd = [
        "buck2",
        "uquery",
        "\"inputs(deps('{}'))\"".format(target),
    ]
    file_paths = str(local(" ".join(cmd))).splitlines()

    return file_paths

# From the Tilt docs:
#
# > By default, Tilt will not let you develop against a remote cluster.
#
# The implication appears to be that if Tilt finds a configured Kubernetes setup on your system
# **and** it's a remote cluster, despite the fact that we are not using any Kubernetes features or
# capabilities, it will still try to connect and fail. Instead, we're going to disable this check
# and continue.
#
# - https://docs.tilt.dev/choosing_clusters.html#remote
# - https://docs.tilt.dev/api.html#api.allow_k8s_contexts
allow_k8s_contexts(k8s_context())

# Use Docker Compose to provide the platform services
docker_compose("./docker-compose.platform.yml")
compose_services = ["jaeger", "nats", "otelcol", "postgres", "postgres-test", "db", "db-test", "grafana", "localstack"]
for service in compose_services:
    if service == "jaeger":
        links = [
            link("http://localhost:16686", "ui"),
        ]
    elif service == "grafana":
        links = [
            link("http://localhost:3000", "ui"),
        ]
    else:
        links = []
    dc_resource(service, links = links, labels = ["platform"])

# Locally build and run `rebaser-server`
rebaser_target = "//bin/rebaser:rebaser"

cmd = "buck2 build @//mode/release {}".format(rebaser_target)
serve_cmd = "buck2 run @//mode/release {}".format(rebaser_target)
if rustc_build_mode == 'standard':
    cmd = "buck2 build {}".format(rebaser_target)
    serve_cmd = "buck2 run {}".format(rebaser_target)
elif debug_no_rebaser_rustc_build_mode:
    cmd = "buck2 build @//mode/release {}".format(rebaser_target)
    serve_cmd = "buck2 run @//mode/release {}".format(rebaser_target)
elif rustc_build_mode == 'debug':
    cmd = "buck2 build @//mode/debug {}".format(rebaser_target)
    serve_cmd = "buck2 run @//mode/debug {}".format(rebaser_target)

local_resource(
    "rebaser",
    labels = ["backend"],
    cmd = cmd,
    serve_cmd = serve_cmd,
    serve_env = {"SI_FORCE_COLOR": "true"},
    allow_parallel = True,
    resource_deps = [
        "nats",
        "otelcol",
        "postgres",
    ],
    deps = _buck2_dep_inputs(rebaser_target),
    trigger_mode = trigger_mode
)

# Locally build and run `module-index`
module_index_target = "//bin/module-index:module-index"

cmd = "buck2 build @//mode/release {}".format(module_index_target)
serve_cmd = "buck2 run @//mode/release {}".format(module_index_target)
if rustc_build_mode == 'standard':
    cmd = "buck2 build {}".format(module_index_target)
    serve_cmd = "buck2 run {}".format(module_index_target)
elif rustc_build_mode == 'debug':
    cmd = "buck2 build @//mode/debug {}".format(module_index_target)
    serve_cmd = "buck2 run @//mode/debug {}".format(module_index_target)

local_resource(
    "module-index",
    labels = ["backend"],
    cmd = cmd,
    serve_cmd = serve_cmd,
    serve_env = {"SI_FORCE_COLOR": "true"},
    allow_parallel = True,
    auto_init = False,
    resource_deps = [
        "otelcol",
        "postgres",
    ],
    deps = _buck2_dep_inputs(module_index_target),
    trigger_mode = trigger_mode,
)

# Locally build and run `pinga`
pinga_target = "//bin/pinga:pinga"

cmd = "buck2 build @//mode/release {}".format(pinga_target)
serve_cmd = "buck2 run @//mode/release {}".format(pinga_target)
if rustc_build_mode == 'standard':
    cmd = "buck2 build {}".format(pinga_target)
    serve_cmd = "buck2 run {}".format(pinga_target)
elif rustc_build_mode == 'debug':
    cmd = "buck2 build @//mode/debug {}".format(pinga_target)
    serve_cmd = "buck2 run @//mode/debug {}".format(pinga_target)

local_resource(
    "pinga",
    labels = ["backend"],
    cmd = cmd,
    serve_cmd = serve_cmd,
    serve_env = {"SI_FORCE_COLOR": "true"},
    allow_parallel = True,
    resource_deps = [
        "nats",
        "otelcol",
        "veritech",
    ],
    deps = _buck2_dep_inputs(pinga_target),
    trigger_mode = trigger_mode,
)

# Locally build and run `veritech`
veritech_target = "//bin/veritech:veritech"

cmd = "buck2 build @//mode/release {}".format(veritech_target)
serve_cmd = "buck2 run @//mode/release {}".format(veritech_target)
if rustc_build_mode == 'standard':
    cmd = "buck2 build {}".format(veritech_target)
    serve_cmd = "buck2 run {}".format(veritech_target)
elif rustc_build_mode == 'debug':
    cmd = "buck2 build @//mode/debug {}".format(veritech_target)
    serve_cmd = "buck2 run @//mode/debug {}".format(veritech_target)

local_resource(
    "veritech",
    labels = ["backend"],
    cmd = cmd,
    serve_cmd = serve_cmd,
    serve_env = {"SI_FORCE_COLOR": "true"},
    # This is the serve command you might need if you want to execute on firecracker for 10 functione executions.
    # NB: BUCK2 MUST RUN AS ROOT OR THIS WILL NOT WORK
    # serve_cmd = "SI_LOG=debug buck2 run {} -- --cyclone-local-firecracker --cyclone-pool-size 10".format(veritech_target),
    allow_parallel = True,
    resource_deps = [
        "nats",
        "otelcol",
    ],
    deps = _buck2_dep_inputs(veritech_target),
    trigger_mode = trigger_mode,
)

# Locally build and run `sdf`
sdf_target = "//bin/sdf:sdf"

cmd = "buck2 build @//mode/release {}".format(sdf_target)
serve_cmd = "buck2 run @//mode/release {}".format(sdf_target)
if rustc_build_mode == 'standard':
    cmd = "buck2 build {}".format(sdf_target)
    serve_cmd = "buck2 run {}".format(sdf_target)
elif rustc_build_mode == 'debug':
    cmd = "buck2 build @//mode/debug {}".format(sdf_target)
    serve_cmd = "buck2 run @//mode/debug {}".format(sdf_target)

local_resource(
    "sdf",
    labels = ["backend"],
    cmd = cmd,
    serve_cmd = serve_cmd,
    serve_env = {"SI_FORCE_COLOR": "true"},
    allow_parallel = True,
    resource_deps = [
        "nats",
        "otelcol",
        "pinga",
        "postgres",
        "veritech",
        "rebaser",
    ],
    deps = _buck2_dep_inputs(sdf_target),
    trigger_mode = trigger_mode,
    readiness_probe = probe(
        period_secs = 5,
        http_get = http_get_action(
            port = 5156,
            path = "/api/",
        ),
    ),
    links = [
        "localhost:5156",
    ],
)

# Locally build and run `web` in dev mode
web_target = "//app/web:dev"
local_resource(
    "web",
    labels = ["frontend"],
    cmd = "buck2 build {}".format(web_target),
    serve_cmd = "buck2 run {}".format(web_target),
    allow_parallel = True,
    resource_deps = [
        "sdf",
    ],
    readiness_probe = probe(
        period_secs = 5,
        http_get = http_get_action(
            port = 8080,
        ),
    ),
    links = [
        link("http://127.0.0.1:8080", "web"),
        link("https://auth.systeminit.com", "auth"),
    ],
)
