load(
    "@prelude-si//:macros.bzl",
    "docker_image",
    "shellcheck",
    "shfmt_check",
    "test_suite",
)

docker_image(
    name = "ci-light",
    srcs = {
        "//:flake.nix": ".",
        "//:flake.lock": ".",
        "//:rust-toolchain": ".",
    },
    build_args = {
        "BASE_VERSION": "12-slim",
        "USER_UID": "2000",
        "USER_GID": "2000",
    },
)
