load("@prelude-si//:macros.bzl", "rust_library")

# TODO(fnichol): fix `canonical_file::test_safe_canonically_join` unit test

rust_library(
    name = "si-settings",
    deps = [
        "//lib/config-file:config-file",
        "//third-party/rust:remain",
        "//third-party/rust:serde",
        "//third-party/rust:serde_with",
        "//third-party/rust:thiserror",
    ],
    srcs = glob(["src/**/*.rs"]),
)
