rust_library(
    name = "si-settings",
    edition = "2021",
    deps = [
        "//lib/config-file:config-file",
        "//third-party/rust:remain",
        "//third-party/rust:serde",
        "//third-party/rust:serde_with",
        "//third-party/rust:thiserror",
    ],
    srcs = glob(["src/**/*.rs"]),
    visibility = ["PUBLIC"],
)
