load("@prelude-si//:macros.bzl", "rust_library")

rust_library(
    name = "nats-multiplexer-client",
    deps = [
        "//lib/nats-multiplexer-core:nats-multiplexer-core",
        "//lib/si-data-nats:si-data-nats",
        "//lib/telemetry-rs:telemetry",
        "//third-party/rust:remain",
        "//third-party/rust:thiserror",
        "//third-party/rust:tokio",
    ],
    srcs = glob([
        "src/**/*.rs",
    ]),
)