include ../../mk/base.mk
include ../../mk/rust.mk

.DEFAULT_GOAL := build
WATCH_PATHS := . \
	../../lib/buck2-resources \
	../../lib/module-index-client \
	../../lib/si-data-pg \
	../../lib/si-posthog-rs \
	../../lib/si-settings \
	../../lib/telemetry-rs
