subscription sshKeyStreamEntityEvents($workspaceId: String!) {
  sshKeyStreamEntityEvents(input:{workspaceId:$workspaceId}) {
    id
    actionName
    entityId
    typeName
    createTime
    updatedTime
    finalTime
    finalized
    outputLines
    errorLines
    success
    inputEntity {
      id
      keyType
      keyFormat
      bits
      state
    }
    outputEntity {
      id
      keyType
      keyFormat
      bits
      fingerprint
      publicKey
      privateKey
      state
    }
  }
}
