# coding: utf-8

"""
    System Initiative API

    The API Server for interacting with a System Initiative workspace

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from system_initiative_api_client.models.execution_history_entry import ExecutionHistoryEntry
from system_initiative_api_client.models.function_execution_status_v1 import FunctionExecutionStatusV1
from typing import Optional, Set
from typing_extensions import Self

class FunctionRelationshipV1(BaseModel):
    """
    FunctionRelationshipV1
    """ # noqa: E501
    depends_on: Optional[List[StrictStr]] = Field(default=None, alias="dependsOn")
    execution_history: Optional[List[ExecutionHistoryEntry]] = Field(default=None, alias="executionHistory")
    execution_status: Optional[FunctionExecutionStatusV1] = Field(default=None, alias="executionStatus")
    function_name: StrictStr = Field(alias="functionName")
    __properties: ClassVar[List[str]] = ["dependsOn", "executionHistory", "executionStatus", "functionName"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FunctionRelationshipV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in execution_history (list)
        _items = []
        if self.execution_history:
            for _item_execution_history in self.execution_history:
                if _item_execution_history:
                    _items.append(_item_execution_history.to_dict())
            _dict['executionHistory'] = _items
        # override the default output from pydantic by calling `to_dict()` of execution_status
        if self.execution_status:
            _dict['executionStatus'] = self.execution_status.to_dict()
        # set to None if execution_status (nullable) is None
        # and model_fields_set contains the field
        if self.execution_status is None and "execution_status" in self.model_fields_set:
            _dict['executionStatus'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FunctionRelationshipV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dependsOn": obj.get("dependsOn"),
            "executionHistory": [ExecutionHistoryEntry.from_dict(_item) for _item in obj["executionHistory"]] if obj.get("executionHistory") is not None else None,
            "executionStatus": FunctionExecutionStatusV1.from_dict(obj["executionStatus"]) if obj.get("executionStatus") is not None else None,
            "functionName": obj.get("functionName")
        })
        return _obj


