/**
 * This file was automatically generated by Nexus 0.11.7
 * Do not make changes to this file directly
 */




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  DataQueryItemsExpressionRequest: { // input type
    comparison?: NexusGenEnums['DataQueryItemsExpressionComparison'] | null; // DataQueryItemsExpressionComparison
    field?: string | null; // String
    fieldType?: NexusGenEnums['DataQueryItemsExpressionFieldType'] | null; // DataQueryItemsExpressionFieldType
    value?: string | null; // String
  }
  DataQueryItemsRequest: { // input type
    expression?: NexusGenInputs['DataQueryItemsExpressionRequest'] | null; // DataQueryItemsExpressionRequest
    query?: NexusGenInputs['DataQueryRequest'][] | null; // [DataQueryRequest!]
  }
  DataQueryRequest: { // input type
    booleanTerm?: NexusGenEnums['DataQueryBooleanTerm'] | null; // DataQueryBooleanTerm
    isNot?: boolean | null; // Boolean
    items?: NexusGenInputs['DataQueryItemsRequest'][] | null; // [DataQueryItemsRequest!]
  }
  KubernetesContainerPortsPortValuesRequest: { // input type
    containerPort?: number | null; // Int
  }
  KubernetesContainerPortsRequest: { // input type
    portValues?: NexusGenInputs['KubernetesContainerPortsPortValuesRequest'] | null; // KubernetesContainerPortsPortValuesRequest
  }
  KubernetesContainerRequest: { // input type
    image?: string | null; // String
    name?: string | null; // String
    ports?: NexusGenInputs['KubernetesContainerPortsRequest'][] | null; // [KubernetesContainerPortsRequest!]
  }
  KubernetesDeploymentConstraintsRequest: { // input type
    componentDisplayName?: string | null; // String
    componentName?: string | null; // String
    kubernetesVersion?: NexusGenEnums['KubernetesDeploymentKubernetesVersion'] | null; // KubernetesDeploymentKubernetesVersion
  }
  KubernetesDeploymentCreateEntityRequest: { // input type
    constraints?: NexusGenInputs['KubernetesDeploymentConstraintsRequest'] | null; // KubernetesDeploymentConstraintsRequest
    description?: string | null; // String
    displayName?: string | null; // String
    name?: string | null; // String
    properties?: NexusGenInputs['KubernetesDeploymentPropertiesRequest'] | null; // KubernetesDeploymentPropertiesRequest
    workspaceId?: string | null; // String
  }
  KubernetesDeploymentEditKubernetesObjectActionRequest: { // input type
    kubernetesObject?: NexusGenInputs['KubernetesDeploymentKubernetesObjectRequest'][] | null; // [KubernetesDeploymentKubernetesObjectRequest!]
  }
  KubernetesDeploymentEditKubernetesObjectYamlActionRequest: { // input type
    kubernetesObjectYaml?: string | null; // String
  }
  KubernetesDeploymentGetComponentRequest: { // input type
    componentId?: string | null; // String
  }
  KubernetesDeploymentGetEntityRequest: { // input type
    entityId?: string | null; // String
  }
  KubernetesDeploymentKubernetesObjectRequest: { // input type
    apiVersion?: string | null; // String
    kind?: string | null; // String
    metadata?: NexusGenInputs['KubernetesMetadataRequest'][] | null; // [KubernetesMetadataRequest!]
    spec?: NexusGenInputs['KubernetesDeploymentKubernetesObjectSpecRequest'] | null; // KubernetesDeploymentKubernetesObjectSpecRequest
  }
  KubernetesDeploymentKubernetesObjectSpecRequest: { // input type
    replicas?: number | null; // Int
    selector?: NexusGenInputs['KubernetesSelectorRequest'][] | null; // [KubernetesSelectorRequest!]
    template?: NexusGenInputs['KubernetesPodTemplateSpecRequest'][] | null; // [KubernetesPodTemplateSpecRequest!]
  }
  KubernetesDeploymentListComponentsRequest: { // input type
    orderBy?: string | null; // String
    orderByDirection?: NexusGenEnums['DataPageTokenOrderByDirection'] | null; // DataPageTokenOrderByDirection
    pageSize?: number | null; // Int
    pageToken?: string | null; // String
    query?: NexusGenInputs['DataQueryRequest'][] | null; // [DataQueryRequest!]
    scopeByTenantId?: string | null; // String
  }
  KubernetesDeploymentListEntitiesRequest: { // input type
    orderBy?: string | null; // String
    orderByDirection?: NexusGenEnums['DataPageTokenOrderByDirection'] | null; // DataPageTokenOrderByDirection
    pageSize?: number | null; // Int
    pageToken?: string | null; // String
    query?: NexusGenInputs['DataQueryRequest'][] | null; // [DataQueryRequest!]
    scopeByTenantId?: string | null; // String
  }
  KubernetesDeploymentPickComponentRequest: { // input type
    constraints?: NexusGenInputs['KubernetesDeploymentConstraintsRequest'] | null; // KubernetesDeploymentConstraintsRequest
  }
  KubernetesDeploymentPropertiesRequest: { // input type
    kubernetesObject?: NexusGenInputs['KubernetesDeploymentKubernetesObjectRequest'] | null; // KubernetesDeploymentKubernetesObjectRequest
    kubernetesObjectYaml?: string | null; // String
  }
  KubernetesDeploymentSyncActionRequest: { // input type
    entityId?: string | null; // String
  }
  KubernetesLabelsRequest: { // input type
    key?: string | null; // String
    value?: string | null; // String
  }
  KubernetesMatchLabelsRequest: { // input type
    key?: string | null; // String
    value?: string | null; // String
  }
  KubernetesMetadataRequest: { // input type
    labels?: NexusGenInputs['KubernetesLabelsRequest'] | null; // KubernetesLabelsRequest
    name?: string | null; // String
  }
  KubernetesPodSpecRequest: { // input type
    containers?: NexusGenInputs['KubernetesContainerRequest'][] | null; // [KubernetesContainerRequest!]
  }
  KubernetesPodTemplateSpecRequest: { // input type
    metadata?: NexusGenInputs['KubernetesMetadataRequest'][] | null; // [KubernetesMetadataRequest!]
    spec?: NexusGenInputs['KubernetesPodSpecRequest'][] | null; // [KubernetesPodSpecRequest!]
  }
  KubernetesSelectorRequest: { // input type
    matchLabels?: NexusGenInputs['KubernetesMatchLabelsRequest'] | null; // KubernetesMatchLabelsRequest
  }
}

export interface NexusGenEnums {
  DataPageTokenOrderByDirection: "ASC" | "DESC"
  DataQueryBooleanTerm: "AND" | "OR"
  DataQueryItemsExpressionComparison: "CONTAINS" | "EQUALS" | "LIKE" | "NOT_EQUALS" | "NOT_LIKE"
  DataQueryItemsExpressionFieldType: "INT" | "STRING"
  EntityEntitySiPropertiesEntityState: "ERROR" | "OK" | "TRANSITION"
  KubernetesDeploymentKubernetesVersion: "V1_12" | "V1_13" | "V1_14" | "V1_15"
}

export interface NexusGenRootTypes {
  ComponentSiProperties: { // root type
    integrationId?: string | null; // String
    integrationServiceId?: string | null; // String
    version?: number | null; // Int
  }
  DataPageToken: { // root type
    containedWithin?: string | null; // String
    itemId?: string | null; // String
    orderBy?: string | null; // String
    orderByDirection?: NexusGenEnums['DataPageTokenOrderByDirection'] | null; // DataPageTokenOrderByDirection
    pageSize?: number | null; // Int
    query?: NexusGenRootTypes['DataQuery'][] | null; // [DataQuery!]
  }
  DataQuery: { // root type
    booleanTerm?: NexusGenEnums['DataQueryBooleanTerm'] | null; // DataQueryBooleanTerm
    isNot?: boolean | null; // Boolean
    items?: NexusGenRootTypes['DataQueryItems'][] | null; // [DataQueryItems!]
  }
  DataQueryItems: { // root type
    expression?: NexusGenRootTypes['DataQueryItemsExpression'] | null; // DataQueryItemsExpression
    query?: NexusGenRootTypes['DataQuery'][] | null; // [DataQuery!]
  }
  DataQueryItemsExpression: { // root type
    comparison?: NexusGenEnums['DataQueryItemsExpressionComparison'] | null; // DataQueryItemsExpressionComparison
    field?: string | null; // String
    fieldType?: NexusGenEnums['DataQueryItemsExpressionFieldType'] | null; // DataQueryItemsExpressionFieldType
    value?: string | null; // String
  }
  DataStorable: { // root type
    naturalKey?: string | null; // String
    tenantIds?: string[] | null; // [String!]
    typeName?: string | null; // String
  }
  EntityEntitySiProperties: { // root type
    billingAccountId?: string | null; // String
    componentId?: string | null; // String
    entityState?: NexusGenEnums['EntityEntitySiPropertiesEntityState'] | null; // EntityEntitySiPropertiesEntityState
    integrationId?: string | null; // String
    integrationServiceId?: string | null; // String
    organizationId?: string | null; // String
    version?: number | null; // Int
    workspaceId?: string | null; // String
  }
  EntityEventEntityEventSiProperties: { // root type
    billingAccountId?: string | null; // String
    componentId?: string | null; // String
    integrationId?: string | null; // String
    integrationServiceId?: string | null; // String
    organizationId?: string | null; // String
    workspaceId?: string | null; // String
  }
  KubernetesContainer: { // root type
    image?: string | null; // String
    name?: string | null; // String
    ports?: NexusGenRootTypes['KubernetesContainerPorts'][] | null; // [KubernetesContainerPorts!]
  }
  KubernetesContainerPorts: { // root type
    portValues?: NexusGenRootTypes['KubernetesContainerPortsPortValues'] | null; // KubernetesContainerPortsPortValues
  }
  KubernetesContainerPortsPortValues: { // root type
    containerPort?: number | null; // Int
  }
  KubernetesDeploymentComponent: { // root type
    constraints?: NexusGenRootTypes['KubernetesDeploymentConstraints'] | null; // KubernetesDeploymentConstraints
    description?: string | null; // String
    displayName?: string | null; // String
    displayTypeName?: string | null; // String
    id?: string | null; // ID
    name?: string | null; // String
    siProperties?: NexusGenRootTypes['ComponentSiProperties'][] | null; // [ComponentSiProperties!]
    siStorable?: NexusGenRootTypes['DataStorable'][] | null; // [DataStorable!]
  }
  KubernetesDeploymentConstraints: { // root type
    componentDisplayName?: string | null; // String
    componentName?: string | null; // String
    kubernetesVersion?: NexusGenEnums['KubernetesDeploymentKubernetesVersion'] | null; // KubernetesDeploymentKubernetesVersion
  }
  KubernetesDeploymentCreateEntityReply: { // root type
    entity?: NexusGenRootTypes['KubernetesDeploymentEntity'] | null; // KubernetesDeploymentEntity
    entityEvent?: NexusGenRootTypes['KubernetesDeploymentEntityEvent'] | null; // KubernetesDeploymentEntityEvent
  }
  KubernetesDeploymentEditKubernetesObjectActionReply: { // root type
    entity?: NexusGenRootTypes['KubernetesDeploymentEntity'] | null; // KubernetesDeploymentEntity
    entityEvent?: NexusGenRootTypes['KubernetesDeploymentEntityEvent'] | null; // KubernetesDeploymentEntityEvent
  }
  KubernetesDeploymentEditKubernetesObjectYamlActionReply: { // root type
    entity?: NexusGenRootTypes['KubernetesDeploymentEntity'] | null; // KubernetesDeploymentEntity
    entityEvent?: NexusGenRootTypes['KubernetesDeploymentEntityEvent'] | null; // KubernetesDeploymentEntityEvent
  }
  KubernetesDeploymentEntity: { // root type
    constraints?: NexusGenRootTypes['KubernetesDeploymentConstraints'] | null; // KubernetesDeploymentConstraints
    displayName?: string | null; // String
    id?: string | null; // ID
    implicitConstraints?: NexusGenRootTypes['KubernetesDeploymentConstraints'] | null; // KubernetesDeploymentConstraints
    name?: string | null; // String
    properties?: NexusGenRootTypes['KubernetesDeploymentProperties'] | null; // KubernetesDeploymentProperties
    siProperties?: NexusGenRootTypes['EntityEntitySiProperties'][] | null; // [EntityEntitySiProperties!]
    siStorable?: NexusGenRootTypes['DataStorable'][] | null; // [DataStorable!]
  }
  KubernetesDeploymentEntityEvent: { // root type
    actionName?: string | null; // String
    createTime?: string | null; // String
    errorLines?: string[] | null; // [String!]
    errorMessage?: string | null; // String
    finalized?: boolean | null; // Boolean
    finalTime?: string | null; // String
    id?: string | null; // ID
    inputEntity?: NexusGenRootTypes['KubernetesDeploymentEntity'] | null; // KubernetesDeploymentEntity
    outputEntity?: NexusGenRootTypes['KubernetesDeploymentEntity'] | null; // KubernetesDeploymentEntity
    previousEntity?: NexusGenRootTypes['KubernetesDeploymentEntity'] | null; // KubernetesDeploymentEntity
    siProperties?: NexusGenRootTypes['EntityEventEntityEventSiProperties'][] | null; // [EntityEventEntityEventSiProperties!]
    siStorable?: NexusGenRootTypes['DataStorable'][] | null; // [DataStorable!]
    success?: boolean | null; // Boolean
    updatedTime?: string | null; // String
  }
  KubernetesDeploymentGetComponentReply: { // root type
    component?: NexusGenRootTypes['KubernetesDeploymentComponent'] | null; // KubernetesDeploymentComponent
  }
  KubernetesDeploymentGetEntityReply: { // root type
    entity?: NexusGenRootTypes['KubernetesDeploymentEntity'] | null; // KubernetesDeploymentEntity
  }
  KubernetesDeploymentKubernetesObject: { // root type
    apiVersion?: string | null; // String
    kind?: string | null; // String
    metadata?: NexusGenRootTypes['KubernetesMetadata'][] | null; // [KubernetesMetadata!]
    spec?: NexusGenRootTypes['KubernetesDeploymentKubernetesObjectSpec'] | null; // KubernetesDeploymentKubernetesObjectSpec
  }
  KubernetesDeploymentKubernetesObjectSpec: { // root type
    replicas?: number | null; // Int
    selector?: NexusGenRootTypes['KubernetesSelector'][] | null; // [KubernetesSelector!]
    template?: NexusGenRootTypes['KubernetesPodTemplateSpec'][] | null; // [KubernetesPodTemplateSpec!]
  }
  KubernetesDeploymentListComponentsReply: { // root type
    items?: NexusGenRootTypes['KubernetesDeploymentComponent'][] | null; // [KubernetesDeploymentComponent!]
    nextPageToken?: string | null; // String
    totalCount?: number | null; // Int
  }
  KubernetesDeploymentListEntitiesReply: { // root type
    items?: NexusGenRootTypes['KubernetesDeploymentEntity'] | null; // KubernetesDeploymentEntity
    nextPageToken?: string | null; // String
    totalCount?: number | null; // Int
  }
  KubernetesDeploymentPickComponentReply: { // root type
    component?: NexusGenRootTypes['KubernetesDeploymentComponent'] | null; // KubernetesDeploymentComponent
    implicitConstraints?: NexusGenRootTypes['KubernetesDeploymentConstraints'] | null; // KubernetesDeploymentConstraints
  }
  KubernetesDeploymentProperties: { // root type
    kubernetesObject?: NexusGenRootTypes['KubernetesDeploymentKubernetesObject'][] | null; // [KubernetesDeploymentKubernetesObject!]
    kubernetesObjectYaml?: string | null; // String
  }
  KubernetesDeploymentSyncActionReply: { // root type
    entity?: NexusGenRootTypes['KubernetesDeploymentEntity'] | null; // KubernetesDeploymentEntity
    entityEvent?: NexusGenRootTypes['KubernetesDeploymentEntityEvent'] | null; // KubernetesDeploymentEntityEvent
  }
  KubernetesLabels: { // root type
    key?: string | null; // String
    value?: string | null; // String
  }
  KubernetesMatchLabels: { // root type
    key?: string | null; // String
    value?: string | null; // String
  }
  KubernetesMetadata: { // root type
    labels?: NexusGenRootTypes['KubernetesLabels'] | null; // KubernetesLabels
    name?: string | null; // String
  }
  KubernetesPodSpec: { // root type
    containers?: NexusGenRootTypes['KubernetesContainer'][] | null; // [KubernetesContainer!]
  }
  KubernetesPodTemplateSpec: { // root type
    metadata?: NexusGenRootTypes['KubernetesMetadata'][] | null; // [KubernetesMetadata!]
    spec?: NexusGenRootTypes['KubernetesPodSpec'][] | null; // [KubernetesPodSpec!]
  }
  KubernetesSelector: { // root type
    matchLabels?: NexusGenRootTypes['KubernetesMatchLabels'] | null; // KubernetesMatchLabels
  }
  Mutation: {};
  Query: {};
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  ID: string;
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
  DataQueryItemsExpressionRequest: NexusGenInputs['DataQueryItemsExpressionRequest'];
  DataQueryItemsRequest: NexusGenInputs['DataQueryItemsRequest'];
  DataQueryRequest: NexusGenInputs['DataQueryRequest'];
  KubernetesContainerPortsPortValuesRequest: NexusGenInputs['KubernetesContainerPortsPortValuesRequest'];
  KubernetesContainerPortsRequest: NexusGenInputs['KubernetesContainerPortsRequest'];
  KubernetesContainerRequest: NexusGenInputs['KubernetesContainerRequest'];
  KubernetesDeploymentConstraintsRequest: NexusGenInputs['KubernetesDeploymentConstraintsRequest'];
  KubernetesDeploymentCreateEntityRequest: NexusGenInputs['KubernetesDeploymentCreateEntityRequest'];
  KubernetesDeploymentEditKubernetesObjectActionRequest: NexusGenInputs['KubernetesDeploymentEditKubernetesObjectActionRequest'];
  KubernetesDeploymentEditKubernetesObjectYamlActionRequest: NexusGenInputs['KubernetesDeploymentEditKubernetesObjectYamlActionRequest'];
  KubernetesDeploymentGetComponentRequest: NexusGenInputs['KubernetesDeploymentGetComponentRequest'];
  KubernetesDeploymentGetEntityRequest: NexusGenInputs['KubernetesDeploymentGetEntityRequest'];
  KubernetesDeploymentKubernetesObjectRequest: NexusGenInputs['KubernetesDeploymentKubernetesObjectRequest'];
  KubernetesDeploymentKubernetesObjectSpecRequest: NexusGenInputs['KubernetesDeploymentKubernetesObjectSpecRequest'];
  KubernetesDeploymentListComponentsRequest: NexusGenInputs['KubernetesDeploymentListComponentsRequest'];
  KubernetesDeploymentListEntitiesRequest: NexusGenInputs['KubernetesDeploymentListEntitiesRequest'];
  KubernetesDeploymentPickComponentRequest: NexusGenInputs['KubernetesDeploymentPickComponentRequest'];
  KubernetesDeploymentPropertiesRequest: NexusGenInputs['KubernetesDeploymentPropertiesRequest'];
  KubernetesDeploymentSyncActionRequest: NexusGenInputs['KubernetesDeploymentSyncActionRequest'];
  KubernetesLabelsRequest: NexusGenInputs['KubernetesLabelsRequest'];
  KubernetesMatchLabelsRequest: NexusGenInputs['KubernetesMatchLabelsRequest'];
  KubernetesMetadataRequest: NexusGenInputs['KubernetesMetadataRequest'];
  KubernetesPodSpecRequest: NexusGenInputs['KubernetesPodSpecRequest'];
  KubernetesPodTemplateSpecRequest: NexusGenInputs['KubernetesPodTemplateSpecRequest'];
  KubernetesSelectorRequest: NexusGenInputs['KubernetesSelectorRequest'];
  DataPageTokenOrderByDirection: NexusGenEnums['DataPageTokenOrderByDirection'];
  DataQueryBooleanTerm: NexusGenEnums['DataQueryBooleanTerm'];
  DataQueryItemsExpressionComparison: NexusGenEnums['DataQueryItemsExpressionComparison'];
  DataQueryItemsExpressionFieldType: NexusGenEnums['DataQueryItemsExpressionFieldType'];
  EntityEntitySiPropertiesEntityState: NexusGenEnums['EntityEntitySiPropertiesEntityState'];
  KubernetesDeploymentKubernetesVersion: NexusGenEnums['KubernetesDeploymentKubernetesVersion'];
}

export interface NexusGenFieldTypes {
  ComponentSiProperties: { // field return type
    integrationId: string | null; // String
    integrationServiceId: string | null; // String
    version: number | null; // Int
  }
  DataPageToken: { // field return type
    containedWithin: string | null; // String
    itemId: string | null; // String
    orderBy: string | null; // String
    orderByDirection: NexusGenEnums['DataPageTokenOrderByDirection'] | null; // DataPageTokenOrderByDirection
    pageSize: number | null; // Int
    query: NexusGenRootTypes['DataQuery'][] | null; // [DataQuery!]
  }
  DataQuery: { // field return type
    booleanTerm: NexusGenEnums['DataQueryBooleanTerm'] | null; // DataQueryBooleanTerm
    isNot: boolean | null; // Boolean
    items: NexusGenRootTypes['DataQueryItems'][] | null; // [DataQueryItems!]
  }
  DataQueryItems: { // field return type
    expression: NexusGenRootTypes['DataQueryItemsExpression'] | null; // DataQueryItemsExpression
    query: NexusGenRootTypes['DataQuery'][] | null; // [DataQuery!]
  }
  DataQueryItemsExpression: { // field return type
    comparison: NexusGenEnums['DataQueryItemsExpressionComparison'] | null; // DataQueryItemsExpressionComparison
    field: string | null; // String
    fieldType: NexusGenEnums['DataQueryItemsExpressionFieldType'] | null; // DataQueryItemsExpressionFieldType
    value: string | null; // String
  }
  DataStorable: { // field return type
    naturalKey: string | null; // String
    tenantIds: string[] | null; // [String!]
    typeName: string | null; // String
  }
  EntityEntitySiProperties: { // field return type
    billingAccountId: string | null; // String
    componentId: string | null; // String
    entityState: NexusGenEnums['EntityEntitySiPropertiesEntityState'] | null; // EntityEntitySiPropertiesEntityState
    integrationId: string | null; // String
    integrationServiceId: string | null; // String
    organizationId: string | null; // String
    version: number | null; // Int
    workspaceId: string | null; // String
  }
  EntityEventEntityEventSiProperties: { // field return type
    billingAccountId: string | null; // String
    componentId: string | null; // String
    integrationId: string | null; // String
    integrationServiceId: string | null; // String
    organizationId: string | null; // String
    workspaceId: string | null; // String
  }
  KubernetesContainer: { // field return type
    image: string | null; // String
    name: string | null; // String
    ports: NexusGenRootTypes['KubernetesContainerPorts'][] | null; // [KubernetesContainerPorts!]
  }
  KubernetesContainerPorts: { // field return type
    portValues: NexusGenRootTypes['KubernetesContainerPortsPortValues'] | null; // KubernetesContainerPortsPortValues
  }
  KubernetesContainerPortsPortValues: { // field return type
    containerPort: number | null; // Int
  }
  KubernetesDeploymentComponent: { // field return type
    constraints: NexusGenRootTypes['KubernetesDeploymentConstraints'] | null; // KubernetesDeploymentConstraints
    description: string | null; // String
    displayName: string | null; // String
    displayTypeName: string | null; // String
    id: string | null; // ID
    name: string | null; // String
    siProperties: NexusGenRootTypes['ComponentSiProperties'][] | null; // [ComponentSiProperties!]
    siStorable: NexusGenRootTypes['DataStorable'][] | null; // [DataStorable!]
  }
  KubernetesDeploymentConstraints: { // field return type
    componentDisplayName: string | null; // String
    componentName: string | null; // String
    kubernetesVersion: NexusGenEnums['KubernetesDeploymentKubernetesVersion'] | null; // KubernetesDeploymentKubernetesVersion
  }
  KubernetesDeploymentCreateEntityReply: { // field return type
    entity: NexusGenRootTypes['KubernetesDeploymentEntity'] | null; // KubernetesDeploymentEntity
    entityEvent: NexusGenRootTypes['KubernetesDeploymentEntityEvent'] | null; // KubernetesDeploymentEntityEvent
  }
  KubernetesDeploymentEditKubernetesObjectActionReply: { // field return type
    entity: NexusGenRootTypes['KubernetesDeploymentEntity'] | null; // KubernetesDeploymentEntity
    entityEvent: NexusGenRootTypes['KubernetesDeploymentEntityEvent'] | null; // KubernetesDeploymentEntityEvent
  }
  KubernetesDeploymentEditKubernetesObjectYamlActionReply: { // field return type
    entity: NexusGenRootTypes['KubernetesDeploymentEntity'] | null; // KubernetesDeploymentEntity
    entityEvent: NexusGenRootTypes['KubernetesDeploymentEntityEvent'] | null; // KubernetesDeploymentEntityEvent
  }
  KubernetesDeploymentEntity: { // field return type
    constraints: NexusGenRootTypes['KubernetesDeploymentConstraints'] | null; // KubernetesDeploymentConstraints
    displayName: string | null; // String
    id: string | null; // ID
    implicitConstraints: NexusGenRootTypes['KubernetesDeploymentConstraints'] | null; // KubernetesDeploymentConstraints
    name: string | null; // String
    properties: NexusGenRootTypes['KubernetesDeploymentProperties'] | null; // KubernetesDeploymentProperties
    siProperties: NexusGenRootTypes['EntityEntitySiProperties'][] | null; // [EntityEntitySiProperties!]
    siStorable: NexusGenRootTypes['DataStorable'][] | null; // [DataStorable!]
  }
  KubernetesDeploymentEntityEvent: { // field return type
    actionName: string | null; // String
    createTime: string | null; // String
    errorLines: string[] | null; // [String!]
    errorMessage: string | null; // String
    finalized: boolean | null; // Boolean
    finalTime: string | null; // String
    id: string | null; // ID
    inputEntity: NexusGenRootTypes['KubernetesDeploymentEntity'] | null; // KubernetesDeploymentEntity
    outputEntity: NexusGenRootTypes['KubernetesDeploymentEntity'] | null; // KubernetesDeploymentEntity
    previousEntity: NexusGenRootTypes['KubernetesDeploymentEntity'] | null; // KubernetesDeploymentEntity
    siProperties: NexusGenRootTypes['EntityEventEntityEventSiProperties'][] | null; // [EntityEventEntityEventSiProperties!]
    siStorable: NexusGenRootTypes['DataStorable'][] | null; // [DataStorable!]
    success: boolean | null; // Boolean
    updatedTime: string | null; // String
  }
  KubernetesDeploymentGetComponentReply: { // field return type
    component: NexusGenRootTypes['KubernetesDeploymentComponent'] | null; // KubernetesDeploymentComponent
  }
  KubernetesDeploymentGetEntityReply: { // field return type
    entity: NexusGenRootTypes['KubernetesDeploymentEntity'] | null; // KubernetesDeploymentEntity
  }
  KubernetesDeploymentKubernetesObject: { // field return type
    apiVersion: string | null; // String
    kind: string | null; // String
    metadata: NexusGenRootTypes['KubernetesMetadata'][] | null; // [KubernetesMetadata!]
    spec: NexusGenRootTypes['KubernetesDeploymentKubernetesObjectSpec'] | null; // KubernetesDeploymentKubernetesObjectSpec
  }
  KubernetesDeploymentKubernetesObjectSpec: { // field return type
    replicas: number | null; // Int
    selector: NexusGenRootTypes['KubernetesSelector'][] | null; // [KubernetesSelector!]
    template: NexusGenRootTypes['KubernetesPodTemplateSpec'][] | null; // [KubernetesPodTemplateSpec!]
  }
  KubernetesDeploymentListComponentsReply: { // field return type
    items: NexusGenRootTypes['KubernetesDeploymentComponent'][] | null; // [KubernetesDeploymentComponent!]
    nextPageToken: string | null; // String
    totalCount: number | null; // Int
  }
  KubernetesDeploymentListEntitiesReply: { // field return type
    items: NexusGenRootTypes['KubernetesDeploymentEntity'] | null; // KubernetesDeploymentEntity
    nextPageToken: string | null; // String
    totalCount: number | null; // Int
  }
  KubernetesDeploymentPickComponentReply: { // field return type
    component: NexusGenRootTypes['KubernetesDeploymentComponent'] | null; // KubernetesDeploymentComponent
    implicitConstraints: NexusGenRootTypes['KubernetesDeploymentConstraints'] | null; // KubernetesDeploymentConstraints
  }
  KubernetesDeploymentProperties: { // field return type
    kubernetesObject: NexusGenRootTypes['KubernetesDeploymentKubernetesObject'][] | null; // [KubernetesDeploymentKubernetesObject!]
    kubernetesObjectYaml: string | null; // String
  }
  KubernetesDeploymentSyncActionReply: { // field return type
    entity: NexusGenRootTypes['KubernetesDeploymentEntity'] | null; // KubernetesDeploymentEntity
    entityEvent: NexusGenRootTypes['KubernetesDeploymentEntityEvent'] | null; // KubernetesDeploymentEntityEvent
  }
  KubernetesLabels: { // field return type
    key: string | null; // String
    value: string | null; // String
  }
  KubernetesMatchLabels: { // field return type
    key: string | null; // String
    value: string | null; // String
  }
  KubernetesMetadata: { // field return type
    labels: NexusGenRootTypes['KubernetesLabels'] | null; // KubernetesLabels
    name: string | null; // String
  }
  KubernetesPodSpec: { // field return type
    containers: NexusGenRootTypes['KubernetesContainer'][] | null; // [KubernetesContainer!]
  }
  KubernetesPodTemplateSpec: { // field return type
    metadata: NexusGenRootTypes['KubernetesMetadata'][] | null; // [KubernetesMetadata!]
    spec: NexusGenRootTypes['KubernetesPodSpec'][] | null; // [KubernetesPodSpec!]
  }
  KubernetesSelector: { // field return type
    matchLabels: NexusGenRootTypes['KubernetesMatchLabels'] | null; // KubernetesMatchLabels
  }
  Mutation: { // field return type
    kubernetesDeploymentCreateEntity: NexusGenRootTypes['KubernetesDeploymentCreateEntityReply'] | null; // KubernetesDeploymentCreateEntityReply
    kubernetesDeploymentEditKubernetesObjectAction: NexusGenRootTypes['KubernetesDeploymentEditKubernetesObjectActionReply'] | null; // KubernetesDeploymentEditKubernetesObjectActionReply
    kubernetesDeploymentEditKubernetesObjectYamlAction: NexusGenRootTypes['KubernetesDeploymentEditKubernetesObjectYamlActionReply'] | null; // KubernetesDeploymentEditKubernetesObjectYamlActionReply
    kubernetesDeploymentSyncAction: NexusGenRootTypes['KubernetesDeploymentSyncActionReply'] | null; // KubernetesDeploymentSyncActionReply
  }
  Query: { // field return type
    kubernetesDeploymentGetComponent: NexusGenRootTypes['KubernetesDeploymentGetComponentReply'] | null; // KubernetesDeploymentGetComponentReply
    kubernetesDeploymentGetEntity: NexusGenRootTypes['KubernetesDeploymentGetEntityReply'] | null; // KubernetesDeploymentGetEntityReply
    kubernetesDeploymentListComponents: NexusGenRootTypes['KubernetesDeploymentListComponentsReply'] | null; // KubernetesDeploymentListComponentsReply
    kubernetesDeploymentListEntities: NexusGenRootTypes['KubernetesDeploymentListEntitiesReply'] | null; // KubernetesDeploymentListEntitiesReply
    kubernetesDeploymentPickComponent: NexusGenRootTypes['KubernetesDeploymentPickComponentReply'] | null; // KubernetesDeploymentPickComponentReply
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    kubernetesDeploymentCreateEntity: { // args
      input?: NexusGenInputs['KubernetesDeploymentCreateEntityRequest'] | null; // KubernetesDeploymentCreateEntityRequest
    }
    kubernetesDeploymentEditKubernetesObjectAction: { // args
      input?: NexusGenInputs['KubernetesDeploymentEditKubernetesObjectActionRequest'] | null; // KubernetesDeploymentEditKubernetesObjectActionRequest
    }
    kubernetesDeploymentEditKubernetesObjectYamlAction: { // args
      input?: NexusGenInputs['KubernetesDeploymentEditKubernetesObjectYamlActionRequest'] | null; // KubernetesDeploymentEditKubernetesObjectYamlActionRequest
    }
    kubernetesDeploymentSyncAction: { // args
      input?: NexusGenInputs['KubernetesDeploymentSyncActionRequest'] | null; // KubernetesDeploymentSyncActionRequest
    }
  }
  Query: {
    kubernetesDeploymentGetComponent: { // args
      input?: NexusGenInputs['KubernetesDeploymentGetComponentRequest'] | null; // KubernetesDeploymentGetComponentRequest
    }
    kubernetesDeploymentGetEntity: { // args
      input?: NexusGenInputs['KubernetesDeploymentGetEntityRequest'] | null; // KubernetesDeploymentGetEntityRequest
    }
    kubernetesDeploymentListComponents: { // args
      input?: NexusGenInputs['KubernetesDeploymentListComponentsRequest'] | null; // KubernetesDeploymentListComponentsRequest
    }
    kubernetesDeploymentListEntities: { // args
      input?: NexusGenInputs['KubernetesDeploymentListEntitiesRequest'] | null; // KubernetesDeploymentListEntitiesRequest
    }
    kubernetesDeploymentPickComponent: { // args
      input?: NexusGenInputs['KubernetesDeploymentPickComponentRequest'] | null; // KubernetesDeploymentPickComponentRequest
    }
  }
}

export interface NexusGenAbstractResolveReturnTypes {
}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames = "ComponentSiProperties" | "DataPageToken" | "DataQuery" | "DataQueryItems" | "DataQueryItemsExpression" | "DataStorable" | "EntityEntitySiProperties" | "EntityEventEntityEventSiProperties" | "KubernetesContainer" | "KubernetesContainerPorts" | "KubernetesContainerPortsPortValues" | "KubernetesDeploymentComponent" | "KubernetesDeploymentConstraints" | "KubernetesDeploymentCreateEntityReply" | "KubernetesDeploymentEditKubernetesObjectActionReply" | "KubernetesDeploymentEditKubernetesObjectYamlActionReply" | "KubernetesDeploymentEntity" | "KubernetesDeploymentEntityEvent" | "KubernetesDeploymentGetComponentReply" | "KubernetesDeploymentGetEntityReply" | "KubernetesDeploymentKubernetesObject" | "KubernetesDeploymentKubernetesObjectSpec" | "KubernetesDeploymentListComponentsReply" | "KubernetesDeploymentListEntitiesReply" | "KubernetesDeploymentPickComponentReply" | "KubernetesDeploymentProperties" | "KubernetesDeploymentSyncActionReply" | "KubernetesLabels" | "KubernetesMatchLabels" | "KubernetesMetadata" | "KubernetesPodSpec" | "KubernetesPodTemplateSpec" | "KubernetesSelector" | "Mutation" | "Query";

export type NexusGenInputNames = "DataQueryItemsExpressionRequest" | "DataQueryItemsRequest" | "DataQueryRequest" | "KubernetesContainerPortsPortValuesRequest" | "KubernetesContainerPortsRequest" | "KubernetesContainerRequest" | "KubernetesDeploymentConstraintsRequest" | "KubernetesDeploymentCreateEntityRequest" | "KubernetesDeploymentEditKubernetesObjectActionRequest" | "KubernetesDeploymentEditKubernetesObjectYamlActionRequest" | "KubernetesDeploymentGetComponentRequest" | "KubernetesDeploymentGetEntityRequest" | "KubernetesDeploymentKubernetesObjectRequest" | "KubernetesDeploymentKubernetesObjectSpecRequest" | "KubernetesDeploymentListComponentsRequest" | "KubernetesDeploymentListEntitiesRequest" | "KubernetesDeploymentPickComponentRequest" | "KubernetesDeploymentPropertiesRequest" | "KubernetesDeploymentSyncActionRequest" | "KubernetesLabelsRequest" | "KubernetesMatchLabelsRequest" | "KubernetesMetadataRequest" | "KubernetesPodSpecRequest" | "KubernetesPodTemplateSpecRequest" | "KubernetesSelectorRequest";

export type NexusGenEnumNames = "DataPageTokenOrderByDirection" | "DataQueryBooleanTerm" | "DataQueryItemsExpressionComparison" | "DataQueryItemsExpressionFieldType" | "EntityEntitySiPropertiesEntityState" | "KubernetesDeploymentKubernetesVersion";

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = "Boolean" | "Float" | "ID" | "Int" | "String";

export type NexusGenUnionNames = never;

export interface NexusGenTypes {
  context: {};
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}