include ../../mk/base.mk
include ../../mk/rust.mk

.DEFAULT_GOAL := build
WATCH_PATHS := . \
	../../lib/cyclone-core \
	../../lib/si-data \
	../../lib/telemetry-rs \
	../../lib/veritech-core \
	../../lib/veritech-server
