[package]
name = "nats-stream-copy-data"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
clap = { workspace = true }
futures = { workspace = true }
si-data-nats = { path = "../../lib/si-data-nats" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
