load("@prelude-si//:macros.bzl", "rust_library")

rust_library(
    name = "data-warehouse-stream-client",
    deps = [
        "//lib/si-aws-config:si-aws-config",
        "//lib/telemetry-rs:telemetry",
        "//third-party/rust:aws-sdk-firehose",
        "//third-party/rust:base64",
        "//third-party/rust:remain",
        "//third-party/rust:thiserror",
        "//third-party/rust:tracing",
    ],
    srcs = glob([
        "src/**/*.rs",
    ]),
)
