load("@prelude-si//:macros.bzl", "mise_install")

mise_install(
    name = "ripgrep_tools",
    packages = [
        "aqua:BurntSushi/ripgrep",
        "aqua:sharkdp/fd",
    ],
    visibility = ["PUBLIC"],
)