load("@prelude-si//:macros.bzl", "rust_library")

rust_library(
    name = "rebaser-core",
    deps = [
        "//third-party/rust:serde",
        "//third-party/rust:ulid",
    ],
    srcs = glob([
        "src/**/*.rs",
    ]),
)
