load("@prelude-si//:macros.bzl", "rust_library")

rust_library(
    name = "rebaser-core",
    deps = [
        "//lib/acceptable:acceptable",
        "//lib/nats-std:nats-std",
        "//lib/si-data-nats:si-data-nats",
        "//lib/si-events-rs:si-events",
        "//third-party/rust:remain",
        "//third-party/rust:serde",
        "//third-party/rust:strum",
    ],
    srcs = glob([
        "src/**/*.rs",
    ]),
)
