rust_library(
    name = "si-test-macros",
    edition = "2021",
    deps = [
        "//third-party/rust:proc-macro2",
        "//third-party/rust:quote",
        "//third-party/rust:syn",
    ],
    srcs = glob(["src/**/*.rs"]),
    proc_macro = True,
    visibility = ["PUBLIC"],
)
