buildscript.run = false

['cfg(target_os = "windows")']
buildscript.run = true
['cfg(target_os = "windows")'.buildscript.prebuilt_cxx_library]
name = "libwindows.a"
static_libs = ["lib/libwindows.a"]
