buildscript.run = false

[platform_fixup.'cfg(target_os = "windows")']
buildscript.run = true
[platform_fixup.'cfg(target_os = "windows")'.buildscript.prebuilt_cxx_library]
name = "libwindows.a"
static_libs = ["lib/libwindows.a"]
