# coding: utf-8

"""
    System Initiative API

    The API Server for interacting with a System Initiative workspace

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from system_initiative_api_client.api.policy_reports_api import PolicyReportsApi


class TestPolicyReportsApi(unittest.TestCase):
    """PolicyReportsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PolicyReportsApi()

    def tearDown(self) -> None:
        pass

    def test_upload_policy_report(self) -> None:
        """Test case for upload_policy_report

        Upload a policy report
        """
        pass


if __name__ == '__main__':
    unittest.main()
