# coding: utf-8

"""
    System Initiative API

    The API Server for interacting with a System Initiative workspace

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from system_initiative_api_client.models.simplified_attribute_diff_v1 import SimplifiedAttributeDiffV1

class TestSimplifiedAttributeDiffV1(unittest.TestCase):
    """SimplifiedAttributeDiffV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SimplifiedAttributeDiffV1:
        """Test SimplifiedAttributeDiffV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SimplifiedAttributeDiffV1`
        """
        model = SimplifiedAttributeDiffV1()
        if include_optional:
            return SimplifiedAttributeDiffV1(
                change_type = '',
                from_schema = True,
                new_source_component_id = '',
                new_source_component_name = '',
                new_source_path = '',
                new_source_prototype = '',
                new_source_type = '',
                new_value = None,
                old_source_component_id = '',
                old_source_component_name = '',
                old_source_path = '',
                old_source_prototype = '',
                old_source_type = '',
                old_value = None
            )
        else:
            return SimplifiedAttributeDiffV1(
                change_type = '',
        )
        """

    def testSimplifiedAttributeDiffV1(self):
        """Test SimplifiedAttributeDiffV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
