# coding: utf-8

"""
    System Initiative API

    The API Server for interacting with a System Initiative workspace

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from system_initiative_api_client.models.update_secret_v1_response import UpdateSecretV1Response

class TestUpdateSecretV1Response(unittest.TestCase):
    """UpdateSecretV1Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateSecretV1Response:
        """Test UpdateSecretV1Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateSecretV1Response`
        """
        model = UpdateSecretV1Response()
        if include_optional:
            return UpdateSecretV1Response(
                secret = system_initiative_api_client.models.secret_v1.SecretV1(
                    definition = 'aws_credentials', 
                    description = 'AWS credentials for production environment', 
                    id = '01HAXYZF3GC9CYA6ZVSM3E4YHH', 
                    name = 'Production AWS Key', )
            )
        else:
            return UpdateSecretV1Response(
                secret = system_initiative_api_client.models.secret_v1.SecretV1(
                    definition = 'aws_credentials', 
                    description = 'AWS credentials for production environment', 
                    id = '01HAXYZF3GC9CYA6ZVSM3E4YHH', 
                    name = 'Production AWS Key', ),
        )
        """

    def testUpdateSecretV1Response(self):
        """Test UpdateSecretV1Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
