# coding: utf-8

"""
    System Initiative API

    The API Server for interacting with a System Initiative workspace

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from system_initiative_api_client.models.delete_component_v1_response import DeleteComponentV1Response

class TestDeleteComponentV1Response(unittest.TestCase):
    """DeleteComponentV1Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteComponentV1Response:
        """Test DeleteComponentV1Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteComponentV1Response`
        """
        model = DeleteComponentV1Response()
        if include_optional:
            return DeleteComponentV1Response(
                status = 'MarkedForDeletion'
            )
        else:
            return DeleteComponentV1Response(
                status = 'MarkedForDeletion',
        )
        """

    def testDeleteComponentV1Response(self):
        """Test DeleteComponentV1Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
