# coding: utf-8

"""
    System Initiative API

    The API Server for interacting with a System Initiative workspace

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from system_initiative_api_client.models.connection_view_v1_one_of3 import ConnectionViewV1OneOf3

class TestConnectionViewV1OneOf3(unittest.TestCase):
    """ConnectionViewV1OneOf3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConnectionViewV1OneOf3:
        """Test ConnectionViewV1OneOf3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConnectionViewV1OneOf3`
        """
        model = ConnectionViewV1OneOf3()
        if include_optional:
            return ConnectionViewV1OneOf3(
                managed_by = system_initiative_api_client.models.managing_connection_view_v1.ManagingConnectionViewV1(
                    component_id = '', 
                    component_name = '', )
            )
        else:
            return ConnectionViewV1OneOf3(
                managed_by = system_initiative_api_client.models.managing_connection_view_v1.ManagingConnectionViewV1(
                    component_id = '', 
                    component_name = '', ),
        )
        """

    def testConnectionViewV1OneOf3(self):
        """Test ConnectionViewV1OneOf3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
