# coding: utf-8

"""
    System Initiative API

    The API Server for interacting with a System Initiative workspace

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from system_initiative_api_client.models.component_review_v1 import ComponentReviewV1

class TestComponentReviewV1(unittest.TestCase):
    """ComponentReviewV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ComponentReviewV1:
        """Test ComponentReviewV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ComponentReviewV1`
        """
        model = ComponentReviewV1()
        if include_optional:
            return ComponentReviewV1(
                action_diffs = [
                    None
                    ],
                attribute_diff_trees = [
                    None
                    ],
                color = '#FF5733',
                diff_status = 'Modified',
                has_resource = True,
                id = '01FXNV4P306V3KGZ73YSVN8A61',
                name = 'My EC2 Instance',
                schema_category = 'AWS::EC2',
                schema_name = 'AWS EC2 Instance'
            )
        else:
            return ComponentReviewV1(
                action_diffs = [
                    None
                    ],
                attribute_diff_trees = [
                    None
                    ],
                diff_status = 'Modified',
                has_resource = True,
                id = '01FXNV4P306V3KGZ73YSVN8A61',
                name = 'My EC2 Instance',
                schema_category = 'AWS::EC2',
                schema_name = 'AWS EC2 Instance',
        )
        """

    def testComponentReviewV1(self):
        """Test ComponentReviewV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
