# coding: utf-8

"""
    System Initiative API

    The API Server for interacting with a System Initiative workspace

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from system_initiative_api_client.models.duplicate_components_v1_response import DuplicateComponentsV1Response

class TestDuplicateComponentsV1Response(unittest.TestCase):
    """DuplicateComponentsV1Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DuplicateComponentsV1Response:
        """Test DuplicateComponentsV1Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DuplicateComponentsV1Response`
        """
        model = DuplicateComponentsV1Response()
        if include_optional:
            return DuplicateComponentsV1Response(
                components = [01H9ZQD35JPMBGHH69BT0Q79AA, 01H9ZQD35JPMBGHH69BT0Q79BB, 01H9ZQD35JPMBGHH69BT0Q79CC]
            )
        else:
            return DuplicateComponentsV1Response(
                components = [01H9ZQD35JPMBGHH69BT0Q79AA, 01H9ZQD35JPMBGHH69BT0Q79BB, 01H9ZQD35JPMBGHH69BT0Q79CC],
        )
        """

    def testDuplicateComponentsV1Response(self):
        """Test DuplicateComponentsV1Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
