# coding: utf-8

"""
    System Initiative API

    The API Server for interacting with a System Initiative workspace

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from system_initiative_api_client.api.debug_funcs_api import DebugFuncsApi


class TestDebugFuncsApi(unittest.TestCase):
    """DebugFuncsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DebugFuncsApi()

    def tearDown(self) -> None:
        pass

    def test_exec_debug_func(self) -> None:
        """Test case for exec_debug_func

        Execute a debug function in the context of a component
        """
        pass

    def test_get_debug_func_state(self) -> None:
        """Test case for get_debug_func_state

        Get debug funcs job state details
        """
        pass


if __name__ == '__main__':
    unittest.main()
