# coding: utf-8

"""
    System Initiative API

    The API Server for interacting with a System Initiative workspace

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from system_initiative_api_client.models.create_variant_qualification_func_v1_request import CreateVariantQualificationFuncV1Request

class TestCreateVariantQualificationFuncV1Request(unittest.TestCase):
    """CreateVariantQualificationFuncV1Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateVariantQualificationFuncV1Request:
        """Test CreateVariantQualificationFuncV1Request
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateVariantQualificationFuncV1Request`
        """
        model = CreateVariantQualificationFuncV1Request()
        if include_optional:
            return CreateVariantQualificationFuncV1Request(
                code = '<!-- String escaped Typescript code here -->',
                description = 'Creates an EC2 Instance',
                display_name = 'Create EC2 Instance',
                locations = [
                    'code'
                    ],
                name = 'awsEC2InstanceCreate'
            )
        else:
            return CreateVariantQualificationFuncV1Request(
                code = '<!-- String escaped Typescript code here -->',
                description = 'Creates an EC2 Instance',
                display_name = 'Create EC2 Instance',
                locations = [
                    'code'
                    ],
                name = 'awsEC2InstanceCreate',
        )
        """

    def testCreateVariantQualificationFuncV1Request(self):
        """Test CreateVariantQualificationFuncV1Request"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
