# coding: utf-8

"""
    System Initiative API

    The API Server for interacting with a System Initiative workspace

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from system_initiative_api_client.models.update_func_v1_request import UpdateFuncV1Request

class TestUpdateFuncV1Request(unittest.TestCase):
    """UpdateFuncV1Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateFuncV1Request:
        """Test UpdateFuncV1Request
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateFuncV1Request`
        """
        model = UpdateFuncV1Request()
        if include_optional:
            return UpdateFuncV1Request(
                code = '<!-- String escaped Typescript code here -->',
                description = 'Updated Description',
                display_name = 'Updated Display Name'
            )
        else:
            return UpdateFuncV1Request(
                code = '<!-- String escaped Typescript code here -->',
                description = 'Updated Description',
                display_name = 'Updated Display Name',
        )
        """

    def testUpdateFuncV1Request(self):
        """Test UpdateFuncV1Request"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
