# coding: utf-8

"""
    System Initiative API

    The API Server for interacting with a System Initiative workspace

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from system_initiative_api_client.api.workspace_management_api import WorkspaceManagementApi


class TestWorkspaceManagementApi(unittest.TestCase):
    """WorkspaceManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkspaceManagementApi()

    def tearDown(self) -> None:
        pass

    def test_create_workspace(self) -> None:
        """Test case for create_workspace

        Create a new workspace
        """
        pass

    def test_delete_workspace(self) -> None:
        """Test case for delete_workspace

        Delete a workspace - please note, this is a soft delete and workspaces can be recovered
        """
        pass

    def test_get_workspace(self) -> None:
        """Test case for get_workspace

        Get the details of a workspace
        """
        pass

    def test_invite_member(self) -> None:
        """Test case for invite_member

        Invite a new member to the workspace
        """
        pass

    def test_list_members(self) -> None:
        """Test case for list_members

        List all members of a workspace
        """
        pass

    def test_list_workspaces(self) -> None:
        """Test case for list_workspaces

        List workspaces
        """
        pass

    def test_remove_member(self) -> None:
        """Test case for remove_member

        Remove a member from the workspace
        """
        pass

    def test_update_member_role(self) -> None:
        """Test case for update_member_role

        Update a member's role in the workspace
        """
        pass

    def test_update_workspace(self) -> None:
        """Test case for update_workspace

        Update the details of a workspace
        """
        pass


if __name__ == '__main__':
    unittest.main()
