# coding: utf-8

"""
    System Initiative API

    The API Server for interacting with a System Initiative workspace

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from system_initiative_api_client.models.component_details_v1 import ComponentDetailsV1

class TestComponentDetailsV1(unittest.TestCase):
    """ComponentDetailsV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ComponentDetailsV1:
        """Test ComponentDetailsV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ComponentDetailsV1`
        """
        model = ComponentDetailsV1()
        if include_optional:
            return ComponentDetailsV1(
                action_functions = [
                    system_initiative_api_client.models.function_relationship_v1.FunctionRelationshipV1(
                        depends_on = [
                            ''
                            ], 
                        execution_history = [
                            system_initiative_api_client.models.execution_history_entry.ExecutionHistoryEntry(
                                func_run_id = '', 
                                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                state = '', )
                            ], 
                        execution_status = system_initiative_api_client.models.function_execution_status_v1.FunctionExecutionStatusV1(
                            action_id = '', 
                            func_run_id = '', 
                            has_active_run = True, 
                            state = '', ), 
                        function_name = '', )
                    ],
                codegen = None,
                component_id = '',
                diff_status = '',
                has_diff = True,
                has_resource = True,
                management_functions = [
                    system_initiative_api_client.models.function_relationship_v1.FunctionRelationshipV1(
                        depends_on = [
                            ''
                            ], 
                        execution_history = [
                            system_initiative_api_client.models.execution_history_entry.ExecutionHistoryEntry(
                                func_run_id = '', 
                                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                state = '', )
                            ], 
                        execution_status = system_initiative_api_client.models.function_execution_status_v1.FunctionExecutionStatusV1(
                            action_id = '', 
                            func_run_id = '', 
                            has_active_run = True, 
                            state = '', ), 
                        function_name = '', )
                    ],
                manages = [
                    system_initiative_api_client.models.management_relationship_v1.ManagementRelationshipV1(
                        to_component_id = '', 
                        to_component_name = '', )
                    ],
                name = '',
                qualification_functions = [
                    system_initiative_api_client.models.function_relationship_v1.FunctionRelationshipV1(
                        depends_on = [
                            ''
                            ], 
                        execution_history = [
                            system_initiative_api_client.models.execution_history_entry.ExecutionHistoryEntry(
                                func_run_id = '', 
                                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                state = '', )
                            ], 
                        execution_status = system_initiative_api_client.models.function_execution_status_v1.FunctionExecutionStatusV1(
                            action_id = '', 
                            func_run_id = '', 
                            has_active_run = True, 
                            state = '', ), 
                        function_name = '', )
                    ],
                resource_id = '',
                resource_status = '',
                schema_name = '',
                subscriptions = [
                    system_initiative_api_client.models.subscription_relationship_v1.SubscriptionRelationshipV1(
                        current_value = null, 
                        from_path = '', 
                        to_component_id = '', 
                        to_component_name = '', 
                        to_path = '', )
                    ]
            )
        else:
            return ComponentDetailsV1(
                component_id = '',
                name = '',
                schema_name = '',
        )
        """

    def testComponentDetailsV1(self):
        """Test ComponentDetailsV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
