# coding: utf-8

"""
    System Initiative API

    The API Server for interacting with a System Initiative workspace

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from system_initiative_api_client.models.subscription_relationship_v1 import SubscriptionRelationshipV1

class TestSubscriptionRelationshipV1(unittest.TestCase):
    """SubscriptionRelationshipV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriptionRelationshipV1:
        """Test SubscriptionRelationshipV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriptionRelationshipV1`
        """
        model = SubscriptionRelationshipV1()
        if include_optional:
            return SubscriptionRelationshipV1(
                current_value = None,
                from_path = '',
                to_component_id = '',
                to_component_name = '',
                to_path = ''
            )
        else:
            return SubscriptionRelationshipV1(
                from_path = '',
                to_component_id = '',
                to_component_name = '',
                to_path = '',
        )
        """

    def testSubscriptionRelationshipV1(self):
        """Test SubscriptionRelationshipV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
