# coding: utf-8

"""
    System Initiative API

    The API Server for interacting with a System Initiative workspace

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from system_initiative_api_client.models.secret_definition_v1 import SecretDefinitionV1

class TestSecretDefinitionV1(unittest.TestCase):
    """SecretDefinitionV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecretDefinitionV1:
        """Test SecretDefinitionV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecretDefinitionV1`
        """
        model = SecretDefinitionV1()
        if include_optional:
            return SecretDefinitionV1(
                form_data = [{name=access_key_id, kind=string}, {name=secret_access_key, kind=password}],
                secret_definition = 'aws_credentials'
            )
        else:
            return SecretDefinitionV1(
                form_data = [{name=access_key_id, kind=string}, {name=secret_access_key, kind=password}],
                secret_definition = 'aws_credentials',
        )
        """

    def testSecretDefinitionV1(self):
        """Test SecretDefinitionV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
