# coding: utf-8

"""
    System Initiative API

    The API Server for interacting with a System Initiative workspace

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from system_initiative_api_client.models.component_prop_view_v1 import ComponentPropViewV1

class TestComponentPropViewV1(unittest.TestCase):
    """ComponentPropViewV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ComponentPropViewV1:
        """Test ComponentPropViewV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ComponentPropViewV1`
        """
        model = ComponentPropViewV1()
        if include_optional:
            return ComponentPropViewV1(
                id = '',
                path = 'path/to/prop',
                prop_id = '',
                value = None
            )
        else:
            return ComponentPropViewV1(
                id = '',
                path = 'path/to/prop',
                prop_id = '',
                value = None,
        )
        """

    def testComponentPropViewV1(self):
        """Test ComponentPropViewV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
