# coding: utf-8

"""
    System Initiative API

    The API Server for interacting with a System Initiative workspace

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from system_initiative_api_client.models.unlocked_schema_v1_response import UnlockedSchemaV1Response

class TestUnlockedSchemaV1Response(unittest.TestCase):
    """UnlockedSchemaV1Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnlockedSchemaV1Response:
        """Test UnlockedSchemaV1Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnlockedSchemaV1Response`
        """
        model = UnlockedSchemaV1Response()
        if include_optional:
            return UnlockedSchemaV1Response(
                schema_id = '01H9ZQD35JPMBGHH69BT0Q79VZ',
                unlocked_variant_id = '01H9ZQD35JPMBGHH69BT0Q75XY'
            )
        else:
            return UnlockedSchemaV1Response(
                schema_id = '01H9ZQD35JPMBGHH69BT0Q79VZ',
                unlocked_variant_id = '01H9ZQD35JPMBGHH69BT0Q75XY',
        )
        """

    def testUnlockedSchemaV1Response(self):
        """Test UnlockedSchemaV1Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
