pub(crate) use test_exclusive_schema_lego_large::migrate_test_exclusive_schema_large_even_lego;
pub(crate) use test_exclusive_schema_lego_large::migrate_test_exclusive_schema_large_odd_lego;
pub(crate) use test_exclusive_schema_lego_medium::migrate_test_exclusive_schema_medium_even_lego;
pub(crate) use test_exclusive_schema_lego_medium::migrate_test_exclusive_schema_medium_odd_lego;
pub(crate) use test_exclusive_schema_lego_small::migrate_test_exclusive_schema_small_even_lego;
pub(crate) use test_exclusive_schema_lego_small::migrate_test_exclusive_schema_small_odd_lego;

mod bricks;
mod test_exclusive_schema_lego_large;
mod test_exclusive_schema_lego_medium;
mod test_exclusive_schema_lego_small;
