load("@prelude-si//:macros.bzl", "rust_library")

rust_library(
    name = "dal-newhotness",
    deps = [
        "//lib/dal:dal",
        "//lib/si-frontend-types-rs:si-frontend-types",
        "//lib/si-id:si-id",
        "//lib/telemetry-rs:telemetry",
        "//third-party/rust:remain",
        "//third-party/rust:serde_json",
        "//third-party/rust:thiserror",
    ],
    srcs = glob([
        "src/**/*.rs",
    ]),
)
