include ../../mk/base.mk
include ../../mk/typescript.mk

.DEFAULT_GOAL := build

test: node_modules ## Tests the TypeScript package
	@echo "--- [$(shell basename ${CURDIR})] $@"
.PHONY: test

lint:
	@echo "skipping lint for now"
