---
services:
  postgres:
    image: 179845983369.dkr.ecr.us-east-2.amazonaws.com/docker-hub/systeminit/postgres:stable
    environment:
      - "POSTGRES_PASSWORD=bugbear"
      - "PGPASSWORD=bugbear"
      - "POSTGRES_USER=si_test"
      - "POSTGRES_DB=si_test"
      - "POSTGRES_MULTIPLE_DBS=si_test_dal,si_test_sdf_server,si_test_layer_db,si_test_audit"
    command:
      - "-c"
      - "fsync=off"
      - "-c"
      - "full_page_writes=off"
    ports:
      - "5432:5432"

  nats:
    image: 179845983369.dkr.ecr.us-east-2.amazonaws.com/docker-hub/systeminit/nats:stable
    command:
      - "--config"
      - "nats-server.conf"
    ports:
      - "4222:4222"
      - "8222:8222"

  otelcol:
    image: 179845983369.dkr.ecr.us-east-2.amazonaws.com/docker-hub/systeminit/otelcol:stable

  spicedb:
    build: ../component/spicedb
    environment:
      - "SPICEDB_LOG_FORMAT=console"
      - "SPICEDB_GRPC_PRESHARED_KEY=hobgoblin"
      - "SPICEDB_DATASTORE_ENGINE=memory"
      - "ZED_KEYRING_PASSWORD=orc"
