rust_library(
    name = "frigg",
    deps = [
        "//lib/si-data-nats:si-data-nats",
        "//lib/si-events-rs:si-events",
        "//lib/si-frontend-types-rs:si-frontend-types",
        "//lib/si-id:si-id",
        "//third-party/rust:bytes",
        "//third-party/rust:remain",
        "//third-party/rust:serde_json",
        "//third-party/rust:thiserror",
    ],
    srcs = glob(["src/**/*.rs"]),
)
