load(
    "@prelude-si//:macros.bzl",
    "docker_image",
)

docker_image(
    name = "jaeger",
    build_args = {
        "BASE_VERSION": "1.43",
    },
    run_docker_args = [
        "--publish",
        "5317:4317",
        "--publish",
        "16686:16686",
    ],
)
