load(
    "@prelude-si//:macros.bzl",
    "docker_image",
)

load("//versions/dockerfiles:jaeger.bzl", "JAEGER_VERSION")

docker_image(
    name = "jaeger",
    build_args = {
        "JAEGER_VERSION": JAEGER_VERSION,
    },
    run_docker_args = [
        "--publish",
        "5317:4317",
        "--publish",
        "16686:16686",
    ],
)
