ARG BASE_VERSION
# As of v2, you no longer need the "all-in-one" image: https://github.com/jaegertracing/jaeger/issues/6321#issuecomment-2607439281
FROM jaegertracing/jaeger:${BASE_VERSION}

ENV COLLECTOR_OTLP_ENABLED=true
