load(
    "@prelude-si//:macros.bzl",
    "docker_image",
)

docker_image(
    name = "rabbitmq",
    build_args = {
        "BASE_VERSION": "3.12-management-alpine",
    },
    run_docker_args = [
        "--publish",
        "5552:5552",
        "--publish",
        "15672:15672",
        "--env",
        "RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_stream advertised_host localhost"
    ],
)
