load(
    "@prelude-si//:macros.bzl",
    "docker_image",
)

load("//versions/dockerfiles:pgbouncer_prom_exporter.bzl", "PGBOUNCER_PROM_EXPORTER_VERSION")

docker_image(
    name = "pgbouncer-prom-exporter",
    build_args = {
        "PGBOUNCER_PROM_EXPORTER_VERSION": PGBOUNCER_PROM_EXPORTER_VERSION,
    },
    srcs = {
        "docker-entrypoint.sh": ".",
        "pgbouncer-conn-string-exporter.sh": ".",
    },
    run_docker_args = [
        "--publish",
        "9127:9127",
    ],
)
