load(
    "@prelude-si//:macros.bzl",
    "container_image",
)

container_image(
    name = "pgbouncer-prom-exporter",
    build_args = {
        "BASE_VERSION": "v0.9.0",
    },
    srcs = {
        "docker-entrypoint.sh": ".",
        "pgbouncer-conn-string-exporter.sh": ".",
    },
    run_docker_args = [
        "--publish",
        "9127:9127",
    ],
    default_target = True,
)
