load(
    "@prelude-si//:macros.bzl",
    "docker_image",
)

docker_image(
    name = "rbe-base",
    srcs = {
        "//:flake.nix": ".",
        "//:flake.lock": ".",
        "//:rust-toolchain": ".",
        "docker-entrypoint.sh": ".",
    },
    build_args = {
        "BASE_VERSION": "12-slim",
        "USER_UID": "2000",
        "USER_GID": "2000",
    },
)
