load(
    "@prelude-si//:macros.bzl",
    "rust_binary",
)

rust_binary(
    name = "read-schema",
    srcs = ["main.rs"],
    crate_root = "main.rs",
    toml_srcs = [],
    deps = [
        "//lib/si-data-spicedb:si-data-spicedb",
        "//third-party/rust:tokio",
        "//third-party/rust:tracing",
        "//third-party/rust:tracing-subscriber",
        "//third-party/rust:url",
    ],
)
