export const AUDIT_LOG_KINDS = [
  "AbandonChangeSet",
  "AddAction",
  "ApplyChangeSet",
  "CancelAction",
  "CreateChangeSet",
  "CreateComponent",
  "CreateSecret",
  "DeleteComponent",
  "DeleteSecret",
  "ExportWorkspace",
  "InstallWorkspace",
  "Login",
  "PutActionOnHold",
  "RetryAction",
  "RunAction",
  "UpdateDependentInputSocket",
  "UpdateDependentOutputSocket",
  "UpdateDependentProperty",
  "UpdatePropertyEditorValue",
  "UpdatePropertyEditorValueForSecret",
  "UpdateSecret",
  "UpgradeComponent",
];

export const AUDIT_LOG_ENTITY_TYPES = [
  "Action",
  "Change Set",
  "Component",
  "Input Socket",
  "Output Socket",
  "Property",
  "Property for Secret",
  "Secret",
  "Workspace",
];
