[package]
name = "veritech"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"

[features]
# TODO(fnichol): remove "client" feature from default
default = ["client", "server"]

client = []

server = [
  "derive_builder",
  "futures-lite",
]

[dependencies]
# server and client
futures = { version = "0.3.17"}
serde = "1.0.123"
serde_json = { version = "1.0.64", features = ["preserve_order"] }
cyclone = { path = "../../pkg/cyclone", default-features = false, features = ["client"] }
si-data = { path = "../../components/si-data" }
# TODO(fnichol): I *think* we can boil this off?
si-settings = { path = "../../components/si-settings" }
thiserror = { version = "1.0" }
tokio = { version = "1.2.0", features = ["full"] }
toml = "0.5"
tracing = { version = "0.1" }

# client only

# server only
derive_builder = { version = "0.10.2", optional = true }
futures-lite = { version = "1.12.0", optional = true }
