protoPackageName = "si.data"

message.QueryComparison.inputType = true
message.QueryBooleanLogic.inputType = true
message.QueryFieldType.inputType = true
message.QueryExpression.inputType = true
message.Query.inputType = true
message.QueryExpressionOption.inputType = true
message.OrderByDirection.inputType = true
message.PageToken.inputType = true

