deps-install:
	@sh -c "'$(CURDIR)/scripts/deps-install.sh'"

run:
	@sh -c "'$(CURDIR)/scripts/run.sh'"

docker-build:
	@sh -c "'$(CURDIR)/scripts/docker-build.sh'"

docker-run:
	@sh -c "'$(CURDIR)/scripts/docker-run.sh'"

docker: docker-build docker-run