load(
    "@prelude-si//:macros.bzl",
    "export_file",
    "test_suite",
    "yapf_check",
)

export_file(
    name = "clippy_output.py",
)

export_file(
    name = "crate_context.py",
)

export_file(
    name = "rustfmt_check.py",
)

export_file(
    name = "generate_rust_metadata.py",
)

yapf_check(
    name = "check-format-python",
    srcs = glob(["**/*.py"]),
)

test_suite(
    name = "check-format",
    tests = [
        ":check-format-python",
    ],
)
