load(
    "@prelude-si//:macros.bzl",
    "export_file",
)

export_file(
    name = "clippy_output.py",
)

export_file(
    name = "crate_context.py",
)

export_file(
    name = "rustfmt_check.py",
)
