load("@prelude-si//:macros.bzl", "rust_library")

rust_library(
    name = "module-index-client",
    deps = [
        "//lib/module-index-types:module-index-types",
        "//lib/si-pkg:si-pkg",
        "//third-party/rust:remain",
        "//third-party/rust:reqwest",
        "//third-party/rust:serde_json",
        "//third-party/rust:thiserror",
        "//third-party/rust:ulid",
        "//third-party/rust:url",
    ],
    srcs = glob([
        "src/**/*.rs",
    ]),
)
