load("@prelude-si//:macros.bzl", "rust_library")

rust_library(
    name = "nats-subscriber",
    deps = [
        "//lib/si-data-nats:si-data-nats",
        "//lib/telemetry-rs:telemetry",
        "//third-party/rust:futures",
        "//third-party/rust:futures-lite",
        "//third-party/rust:pin-project-lite",
        "//third-party/rust:remain",
        "//third-party/rust:serde",
        "//third-party/rust:serde_json",
        "//third-party/rust:thiserror",
        "//third-party/rust:tokio",
    ],
    srcs = glob(["src/**/*.rs"]),
)
