query kubernetesDeploymentPickComponent($input: KubernetesDeploymentPickComponentRequest) {
  kubernetesDeploymentPickComponent(input:$input) {
    component {
      id
      displayName
      kubernetesVersion
    }
    implicitConstraints {
      field
      value
    }
  }
}

