load("@prelude-si//:macros.bzl", "rust_library")

rust_library(
    name = "auth-api-client",
    deps = [
        "//lib/si-id:si-id",

        "//third-party/rust:remain",
        "//third-party/rust:reqwest",
        "//third-party/rust:serde",
        "//third-party/rust:serde_json",
        "//third-party/rust:thiserror",
        "//third-party/rust:ulid",
        "//third-party/rust:url",
    ],
    srcs = glob([
        "src/**/*.rs",
    ]),
)
