query sshKeyPickComponent(
  $input: SshKeyPickComponentRequest 
) {
  sshKeyPickComponent(input:$input) {
    component {
      id
      displayName
      keyType
      keyFormat
      bits
    }
    implicitConstraints {
      field
      value
    }
  }
}

