# Use an allow-list strategy vs and ignore-list strategy to only include what
# is necessary and no more for less unnecessary rebuilds.
#
# See: https://kevinpollet.dev/posts/how-to-use-your-dockerignore-as-a-whitelist/

# Ignore everything
*

# All components required to build
!component/postgres

# Ignore non-portable context in component sub-directories
**/.envrc
**/Makefile
**/script
**/target
**/tmp

