// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyOrIndex } from "./KeyOrIndex";

export type AttributeValuePath = { "prop": { path: string, key_or_index: KeyOrIndex | null, } } | { "inputSocket": string } | { "outputSocket": string };
