// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SchemaVariantSpecComponentType } from "./SchemaVariantSpecComponentType";

export type SchemaVariantSpecData = {
  version: string;
  link: string | null;
  color: string | null;
  displayName: string | null;
  componentType: SchemaVariantSpecComponentType;
  funcUniqueId: string;
  description: string | null;
};
