protoPackageName = "si.kubernetes.deployment"

service.KubernetesDeployment.GetComponent.query = true
service.KubernetesDeployment.ListComponents.query = true
service.KubernetesDeployment.PickComponent.query = true
service.KubernetesDeployment.ListEntities.query = true
service.KubernetesDeployment.GetEntity.query = true
service.KubernetesDeployment.ListEntityEvents.query = true

service.KubernetesDeployment.CreateEntity.mutation = true
service.KubernetesDeployment.EditPropObject.mutation = true
service.KubernetesDeployment.EditPropObjectYaml.mutation = true
service.KubernetesDeployment.SyncEntity.mutation = true

message.EntityEvent.implementsInterfaceTypeHint = ["EntityEvent"]

[message.Component.integrationId.has_one]
to = "integration"
grpcServiceName = "Account"
method = "GetIntegration"
type = "Integration"

[message.Component.integrationServiceId.has_one]
to = "integrationService"
grpcServiceName = "Account"
method = "GetIntegrationService"
type = "IntegrationService"

[message.Entity.integrationId.has_one]
to = "integration"
grpcServiceName = "Account"
method = "GetIntegration"
type = "Integration"

[message.Entity.integrationServiceId.has_one]
to = "integrationService"
grpcServiceName = "Account"
method = "GetIntegrationService"
type = "IntegrationService"

[message.Entity.workspaceId.has_one]
to = "workspace"
grpcServiceName = "Account"
method = "GetWorkspace"
type = "Workspace"

[message.Entity.organizationId.has_one]
to = "organization"
grpcServiceName = "Account"
method = "GetOrganization"
type = "Organization"

[message.Entity.billingAccountId.has_one]
to = "billingAccount"
grpcServiceName = "Account"
method = "GetBillingAccount"
type = "BillingAccount"

[[message.Entity.id.has_many]]
to = "entityEvents"
grpcServiceName = "KubernetesDeployment"
method = "kubernetesDeploymentListEntityEvents"
type = "KubernetesDeploymentListEntityEventsReply"
inputType = "KubernetesDeploymentListEntityEventsRequest"

[message.EntityEvent.entityId.has_one]
to = "entity"
grpcServiceName = "KubernetesDeployment"
method = "GetEntity"
type = "KubernetesDeploymentEntity"

[message.EntityEvent.userId.has_one]
to = "user"
grpcServiceName = "Account"
method = "GetUser"
type = "User"

