[package]
name = "bytes-lines-codec"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"

[dependencies]
bytes = "1.1.0"
tokio-util = { version = "0.6.8", features = ["codec"] }

[dev-dependencies]
futures = "0.3.17"
serde = { version = "1.0.130", features = ["derive"] }
tokio = { version = "1.12.0", features = ["full"] }
tokio-serde = { version = "0.8.0", features = ["json"] }
