load("@prelude-si//:macros.bzl", "rust_library")

rust_library(
    name = "innit-core",
    deps = [
        "//lib/config-file:config-file",
        "//third-party/rust:aws-sdk-ssm",
        "//third-party/rust:serde"
    ],
    srcs = glob([
        "src/**/*.rs",
    ]),
)
