load(
    "@prelude-si//:macros.bzl",
    "container_image",
)

container_image(
    name = "versitygw",
    image_name = "versitygw",
    srcs = {
        "init-buckets.sh": ".",
    },
    default_target = True,
)
