load("@prelude-si//:macros.bzl", "rust_library")

rust_library(
    name = "bedrock-core",
    deps = [
        "//lib/si-data-nats:si-data-nats",

        "//third-party/rust:async-trait",
        "//third-party/rust:serde",
        "//third-party/rust:serde_json",
    ],
    srcs = glob([
        "src/**/*.rs",
    ]),
)
