load("@prelude-si//:macros.bzl", "rust_library")

rust_library(
    name = "veritech-core",
    deps = [
        "//lib/cyclone-core:cyclone-core",
        "//lib/nats-std:nats-std",
        "//lib/si-crypto:si-crypto",
        "//lib/si-data-nats:si-data-nats",
        "//third-party/rust:serde_json",
        "//third-party/rust:thiserror",
    ],
    test_unit_deps = [
        "//lib/si-std:si-std",
    ],
    srcs = glob(["src/**/*.rs"]),
)
