include ../../mk/base.mk
include ../../mk/rust.mk

.DEFAULT_GOAL := build
WATCH_PATHS := . \
	../../lib/cyclone-client \
	../../lib/cyclone-core \
	../../lib/cyclone-server \
	../../lib/deadpool-cyclone \
	../../lib/si-data \
	../../lib/si-settings \
	../../lib/telemetry-rs
