load(
    "@prelude-si//:macros.bzl",
    "docker_image",
)

load("//versions/dockerfiles:nats.bzl", "NATS_VERSION")

docker_image(
    name = "nats",
    srcs = {
        "nats-server.conf": "component/nats",
    },
    build_args = {
        "NATS_VERSION": NATS_VERSION,
    },
    run_docker_args = [
        "--publish",
        "4222:4222",
        "--publish",
        "8222:8222",
    ],
    run_container_args = [
        "--config",
        "nats-server.conf",
    ],
)
