load("@prelude-si//:macros.bzl", "rust_library")

rust_library(
    name = "content-store-test",
    deps = [
        "//lib/content-store:content-store",
        "//lib/si-data-pg:si-data-pg",
        "//lib/telemetry-rs:telemetry",
        "//third-party/rust:color-eyre",
        "//third-party/rust:uuid",
    ],
    srcs = glob(["src/**/*.rs"]),
)