load("@prelude-si//:macros.bzl", "rust_library")

rust_library(
    name = "buck2-resources",
    deps = [
        "//third-party/rust:serde_json",
        "//third-party/rust:thiserror",
    ],
    srcs = glob([
        "src/**/*.rs",
    ]),
)
