rust_library(
    name = "si-posthog",
    edition = "2021",
    deps = [
        "//lib/telemetry-rs:telemetry",
        "//third-party/rust:derive_builder",
        "//third-party/rust:reqwest",
        "//third-party/rust:serde",
        "//third-party/rust:serde_json",
        "//third-party/rust:thiserror",
        "//third-party/rust:tokio",
    ],
    srcs = glob(["src/**/*.rs"]),
    visibility = ["PUBLIC"],
)
