load(
    "@prelude-si//:macros.bzl",
    "container_image",
)

container_image(
    name = "pgbouncer",
    build_args = {
        "BASE_VERSION": "1.22.1-p0",
    },
    run_docker_args = [
        "--publish",
        "5432:5432",
    ],
    default_target = True,
)
