load(
    "@prelude-si//:macros.bzl",
    "docker_image",
)

load("//versions/dockerfiles:pgbouncer.bzl", "PGBOUNCER_VERSION")

docker_image(
    name = "pgbouncer",
    build_args = {
        "PGBOUNCER_VERSION": PGBOUNCER_VERSION,
    },
    run_docker_args = [
        "--publish",
        "5432:5432",
    ],
)
