sources:
  docker:
    type: "docker_logs"
  $SI_SERVICE-journal:
    type: "journald"
    include_units: ["$SI_SERVICE"]
    journal_directory: "/var/log/journal"
  sdf-migration:
    type: "journald"
    include_matches:
      SYSLOG_IDENTIFIER: ["sdf-migration"]
    journal_directory: "/var/log/journal"

transforms:
  honeycomb_format:
    type: remap
    inputs: ["$SI_SERVICE-journal", "sdf-migration"]
    source: |-
      if exists(.message) {
        message = string!(.message)

        if contains(message, "ERROR") {
          .level = "error"
        } else if contains(message, "WARN") {
          .level = "warn"
        } else if contains(message, "DEBUG") {
          .level = "debug"
        } else if contains(message, "TRACE") {
          .level = "trace"
        } else {
          .level = "info"
        }
      }

sinks:
  cloudwatch:
    type: "aws_cloudwatch_logs"
    inputs: ["$SI_SERVICE-journal", "sdf-migration"]
    compression: "gzip"
    encoding:
      codec: "text"
    region: "us-east-1"
    group_name: "/ec2/$SI_HOSTENV-$SI_SERVICE"
    stream_name: "{{ host }}"
  cloudwatch:
    type: "aws_cloudwatch_logs"
    inputs: ["docker"]
    compression: "gzip"
    encoding:
      codec: "text"
    region: "us-east-1"
    group_name: "/ec2/$SI_HOSTENV-$SI_SERVICE-docker"
    stream_name: "{{ host }}"
  honeycomb:
    type: "honeycomb"
    inputs: ["honeycomb_format"]
    api_key: "$SI_HONEYCOMB_API_KEY"
    dataset: "$SI_SERVICE"
