---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

secretGenerator:
  - name: postgres
    type: Opaque
    envs:
      - postgres.env

resources:
  - postgres-statefulSet.yaml
  - postgres-service.yaml
