load(
    "@prelude-si//:macros.bzl",
    "export_file",
)

export_file(
    name = "capture_stdout.py",
)

export_file(
    name = "docker_build_context.py",
)

export_file(
    name = "docker_container_run.py",
)

export_file(
    name = "docker_image_build.py",
)

export_file(
    name = "docker_image_push.py",
)

export_file(
    name = "docker_image_promote.py",
)
