[package]
name = "openapi-extractor"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "openapi-extractor"
path = "src/main.rs"

[dependencies]
luminork-server = { path = "../../lib/luminork-server" }
serde_json = { workspace = true }
tokio = { workspace = true }
