load(
    "@prelude-si//:macros.bzl",
    "container_image",
)

container_image(
    name = "lambda",
    srcs = {
        "docker-entrypoint.sh": ".",
        "functions/": ".",
    },
    default_target = True,
)
