load("@prelude-si//:macros.bzl", "rust_library")

rust_library(
    name = "si-id",
    deps = [
        "//third-party/rust:lazy_static",
        "//third-party/rust:snowdon",
    ],
    srcs = glob([
        "src/**/*.rs",
    ]),
)
