load("@prelude-si//:macros.bzl", "rust_library")

rust_library(
    name = "tokio-watchdog",
    deps = [
        "//lib/telemetry-rs:telemetry",
        "//lib/telemetry-utils-rs:telemetry-utils",
        "//third-party/rust:tokio",
        "//third-party/rust:tokio-util",
    ],
    srcs = glob(["src/**/*.rs"]),
)
