load("@prelude-si//:macros.bzl", "rust_library")

rust_library(
    name = "telemetry",
    deps = [
        "//third-party/rust:async-trait",
        "//third-party/rust:opentelemetry",
        "//third-party/rust:remain",
        "//third-party/rust:thiserror",
        "//third-party/rust:tokio",
        "//third-party/rust:tokio-util",
        "//third-party/rust:tracing",
        "//third-party/rust:tracing-opentelemetry",
    ],
    srcs = glob(["src/**/*.rs"]),
)
