rust_library(
    name = "si-data-nats",
    edition = "2021",
    deps = [
        "//lib/telemetry-rs:telemetry",
        "//third-party/rust:crossbeam-channel",
        "//third-party/rust:futures",
        "//third-party/rust:nats",
        "//third-party/rust:remain",
        "//third-party/rust:serde",
        "//third-party/rust:serde_json",
        "//third-party/rust:thiserror",
        "//third-party/rust:tokio",
    ],
    srcs = glob(["src/**/*.rs"]),
    visibility = ["PUBLIC"],
)
