subscription awsEksClusterRuntimeStreamEntityEvents($workspaceId: String!) {
  awsEksClusterRuntimeStreamEntityEvents(input:{workspaceId:$workspaceId}) {
    id
    actionName
    entityId
    typeName
    createTime
    updatedTime
    finalTime
    finalized
    outputLines
    errorLines
    success
    inputEntity {
      id
      kubernetesVersion
      state
    }
    outputEntity {
      id
      kubernetesVersion
      state
    }
  }
}

