export { registry } from "../registry";
export { PropBool } from "../prop/bool";
export { PropCode } from "../prop/code";
export { PropEnum } from "../prop/enum";
export { PropLink } from "../prop/link";
export { PropMap } from "../prop/map";
export { PropNumber } from "../prop/number";
export { PropSelect } from "../prop/select";
export { PropText } from "../prop/text";
export { Props, PropObject, PropAction, PropMethod } from "../attrList";
