include ../../mk/base.mk
include ../../mk/rust.mk

.DEFAULT_GOAL := build
WATCH_PATHS := . \
	../../lib/deadpool-cyclone \
	../../lib/si-data-nats \
	../../lib/si-settings \
	../../lib/telemetry-rs \
	../../lib/veritech-core
