load(
    "@prelude-si//:macros.bzl",
    "rust_binary",
)

rust_binary(
    name = "dal-pkg-export",
    srcs = ["main.rs"],
    crate_root = "main.rs",
    toml_srcs = [],
    deps = [
        "//third-party/rust:tokio",
    ],
    resources = {
        "dev.encryption.key": "//lib/veritech-server:dev.encryption.key",
    }
)
