---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whiskers-deployment
  labels:
    app: whiskers
spec:
  selector:
    matchLabels:
      app: whiskers
  template:
    metadata:
      labels:
        app: whiskers
    spec:
      containers:
        - name: whiskers
          image: systeminit/whiskers
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
