load(
    "@prelude-si//:macros.bzl",
    "rust_binary",
)

rust_binary(
    name = "nats-core-subscriber",
    srcs = ["main.rs"],
    crate_root = "main.rs",
    toml_srcs = [],
    deps = [
        "//lib/naxum:naxum",
        "//third-party/rust:async-nats",
        "//third-party/rust:futures",
        "//third-party/rust:tokio",
        "//third-party/rust:tokio-util",
        "//third-party/rust:tower",
        "//third-party/rust:tracing",
        "//third-party/rust:tracing-subscriber",
    ],
)
