load("@prelude-si//:macros.bzl", "rust_library")

rust_library(
    name = "joi-validator",
    deps = [
        "//third-party/rust:chrono",
        "//third-party/rust:remain",
        "//third-party/rust:serde",
        "//third-party/rust:serde_json",
        "//third-party/rust:serde_with",
        "//third-party/rust:thiserror",
    ],
    srcs = glob([
        "src/**/*.rs",
    ]),
    test_unit_deps = [
        "//third-party/rust:color-eyre",
    ],
)
