# Use an allow-list strategy vs and ignore-list strategy to only include what
# is necessary and no more for less unnecessary rebuilds.

# Ignore everything
*

# Root/common files
!.prettierrc.js
!babel.config.js

# All components required to build
!app/web

# Ignore non-portable context in component sub-directories
**/.envrc
**/tmp
**/node_modules
app/*/dist
app/*/script
app/*/Makefile
