# Use an allow-list strategy vs and ignore-list strategy to only include what
# is necessary and no more for less unnecessary rebuilds.

# Ignore everything
*

# Root/common files
!package.json
!pnpm-lock.yaml
!pnpm-workspace.yaml

# All components required to build
!app/web
!lib/tsconfig
!lib/eslint-config
!lib/vue-lib
!lib/ts-lib

# Ignore non-portable context in component sub-directories
**/.envrc
**/tmp
**/node_modules
app/*/dist
app/*/script
app/*/Makefile
