omit_targets = []
extra_srcs = []
omit_srcs = []
rustc_flags = []
cfgs = []
features = []
omit_features = []
extra_deps = []
omit_deps = []
cargo_env = false
linker_flags = []

[rustc_flags_select]

[env]

[[buildscript]]
[buildscript.rustc_flags]

[extra_mapped_srcs]

[platform_fixup.'cfg(target_os = "macos")']
features = ["libfuse"]
extra_deps = [":pkg-config"]
