load(
    "@prelude-si//:macros.bzl",
    "docker_image",
)

docker_image(
    name = "otelcol",
    srcs = {
        "config.yaml": ".",
        "honeycomb-config.yaml": ".",
        "docker-entrypoint.sh": ".",
    },
    build_args = {
        "BASE_VERSION": "0.102.1",
    },
    run_docker_args = [
        "--publish",
        "4317:4317",
        "--publish",
        "4318:4318",
        "--publish",
        "55679:55679",
    ],
)
