include ../../mk/base.mk
include ../../mk/rust.mk

.DEFAULT_GOAL := build
WATCH_PATHS := . \
	../../lib/dal \
	../../lib/si-data-faktory \
	../../lib/si-data-nats \
	../../lib/si-data-pg \
	../../lib/si-settings \
	../../lib/si-std \
	../../lib/si-test-macros \
	../../lib/telemetry-rs \
	../../lib/veritech-client
