load(
    "@prelude-si//:macros.bzl",
    "docker_image",
)
load("//versions/dockerfiles:alpine.bzl", "ALPINE_WITH_MINOR_VERSION")

docker_image(
    name = "init",
    srcs = {
        "docker-entrypoint.sh": ".",
        "configs/": ".",
    },
    build_args = {
        "ALPINE_VERSION": ALPINE_WITH_MINOR_VERSION,
    },
)
