---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol
data:
  config.yaml: |
    ---
    receivers:
      otlp:
        protocols:
          grpc:

    processors:
      batch:
      probabilistic_sampler:
        sampling_percentage: 10
        hash_seed: 42

    exporters:
      logging:
        loglevel: "warn"
      otlp:
        endpoint: "api.honeycomb.io:443"
        headers:
          "x-honeycomb-team": "${HONEYCOMB_TOKEN}"
          "x-honeycomb-dataset": "${HONEYCOMB_DATASET}"

    extensions:
      health_check:
      pprof:
      zpages:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [probabilistic_sampler, batch]
          exporters: [logging, otlp]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, otlp]
      extensions: [health_check, pprof, zpages]
