---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: systeminit/si-web-app:20210813.211006.0-sha.7d335fa6
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: dockerhub
      restartPolicy: Always
