global:
  scrape_interval: 100ms
scrape_configs:
 - job_name: metrics
   static_configs:
    - targets:
       - otelcol:9090
 - job_name: node-exporter
   static_configs:
    - targets:
       - node_exporter:9100
