scrape_configs:
  - job_name: otelcol-metrics
    scrape_interval: 100ms
    scrape_timeout: 10ms
    static_configs:
      - targets:
          - otelcol:9090
  - job_name: node-exporter
    scrape_interval: 1s
    scrape_timeout: 400ms
    static_configs:
      - targets:
          - node_exporter:9100
