load(
    "@prelude-si//:macros.bzl",
    "export_file",
    "test_suite",
    "yapf_check",
)

export_file(
    name = "git_info.py",
)

yapf_check(
    name = "check-format-python",
    srcs = glob(["**/*.py"]),
)

test_suite(
    name = "check-format",
    tests = [
        ":check-format-python",
    ],
)
