name: Push Clover Assets

on:
  push:
    branches:
      - main
    paths:
      - 'bin/clover/**'
      - 'bin/hoist/**'
      - 'lib/jsr-systeminit/cf-db/**'

jobs:
  push-assets:
    runs-on: ubuntu-latest
    env:
      SI_BEARER_TOKEN: ${{ secrets.SI_BEARER_TOKEN }}
      SI_MODULE_INDEX_URL: "https://module-index.systeminit.com"
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - uses: dtolnay/rust-toolchain@stable

      - name: Generate Specs
        run: |
          cd bin/clover
          LOG_LEVEL=debug deno task run generate-specs

      - name: Push Specs
        run: |
          cd bin/hoist
          cargo run -- upload-all-specs -y --non-interactive --max-concurrent 25 -t ../clover/si-specs
