name: Base Image Rebuild
on:
  schedule:
    - cron: '1 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env: 
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Release new base build image
      run: make release//base
    - name: Notify slack
      if: success()
      uses: pullreminders/slack-action@v1.0.7
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACKBOT_TOKEN }}
        with:
          args: '{\"channel\":\"engineering\",\"text\":\"Base image rebuilt!\"}'
    - name: Notify slack
      if: failure()
      uses: pullreminders/slack-action@v1.0.7
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACKBOT_TOKEN }}
        with:
          args: '{\"channel\":\"engineering\",\"text\":\"@here Base image rebuild failed - better check it out. :)\"}'
