name: Base Image Rebuild
on:
  schedule:
    - cron: '1 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env: 
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Release new base build image
      run: make release//base
