name: build-docker-images

on:
  push:
    branches:
      - staging
      - trying

jobs:
  check-changes:
    name: Check changed paths
    runs-on: self-hosted
    outputs:
      nats-changed: ${{ steps.check-component-changes.outputs.nats }}
      otelcol-changed: ${{ steps.check-component-changes.outputs.otelcol }}
      postgres-changed: ${{ steps.check-component-changes.outputs.postgres }}
      sdf-changed: ${{ steps.check-component-changes.outputs.sdf }}
      veritech-changed: ${{ steps.check-component-changes.outputs.veritech }}
      web-changed: ${{ steps.check-component-changes.outputs.web }}
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2.3.4
        with:
          fetch-depth: 1000
      - id: check-component-changes
        run: ./ci/scripts/check-for-component-changes.sh
  nats:
    name: "Build nats image"
    needs: check-changes
    if: needs.check-changes.outputs.nats-changed == 'true'
    uses: ./.github/workflows/build-docker-image.yml
    with:
      component_name: nats
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  otelcol:
    name: "Build otelcol image"
    needs: check-changes
    if: needs.check-changes.outputs.otelcol-changed == 'true'
    uses: ./.github/workflows/build-docker-image.yml
    with:
      component_name: otelcol
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  postgres:
    name: "Build postgres image"
    needs: check-changes
    if: needs.check-changes.outputs.postgres-changed == 'true'
    uses: ./.github/workflows/build-docker-image.yml
    with:
      component_name: postgres
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  sdf:
    name: "Build sdf image"
    needs: check-changes
    if: needs.check-changes.outputs.sdf-changed == 'true'
    uses: ./.github/workflows/build-docker-image.yml
    with:
      component_name: sdf
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  veritech:
    name: "Build veritech image"
    needs: check-changes
    if: needs.check-changes.outputs.veritech-changed == 'true'
    uses: ./.github/workflows/build-docker-image.yml
    with:
      component_name: veritech
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  web:
    name: "Build postgres image"
    needs: check-changes
    if: needs.check-changes.outputs.web-changed == 'true'
    uses: ./.github/workflows/build-docker-image.yml
    with:
      component_name: web
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  summary:
    name: Docker Image Build Summary Status
    runs-on: self-hosted
    needs:
      - check-changes
      - nats
      - otelcol
      - postgres
      - sdf
      - veritech
      - web
    if: always()
    env:
      CHECK_CHANGES_STATUS: ${{ needs.check-changes.result }}
      NATS_RUN: ${{ needs.check-changes.outputs.nats-changed }}
      OTELCOL_RUN: ${{ needs.check-changes.outputs.otelcol-changed }}
      POSTGRES_RUN: ${{ needs.check-changes.outputs.postgres-changed }}
      SDF_RUN: ${{ needs.check-changes.outputs.sdf-changed }}
      VERITECH_RUN: ${{ needs.check-changes.outputs.veritech-changed }}
      WEB_RUN: ${{ needs.check-changes.outputs.web-changed }}
      NATS_STATUS: ${{ needs.nats.result }}
      OTELCOL_STATUS: ${{ needs.otelcol.result }}
      POSTGRES_STATUS: ${{ needs.postgres.result }}
      SDF_STATUS: ${{ needs.sdf.result }}
      VERITECH_STATUS: ${{ needs.veritech.result }}
      WEB_STATUS: ${{ needs.web.result }}
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2.3.4
      - id: check-build-statuses
        run: ./ci/scripts/check-image-build-statuses.sh
