name: build-docker-image

on:
  workflow_call:
    inputs:
      component_name:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  build-image:
    name: Build ${{ inputs.component_name }} Docker Image
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2.3.4
      - id: buildx
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25 # pin@v1.6.0
      - id: login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9 # pin@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - id: release
        name: make release-${{ inputs.component_name }}
        run: |
          : make release-${{ inputs.component_name }}
          echo "::group::Building and publishing image"
          make release-${{ inputs.component_name }}
          echo "::endgroup::"
          echo "::group::Manifest info"
          jq . <tmp/release-${{ inputs.component_name }}.manifest.json
          echo "::endgroup::"
          echo "::set-output name=manifest::$(
            cat tmp/release-${{ inputs.component_name }}.manifest.json
          )"
      - name: report
        if: success()
        run: |
          : report
          echo 'DockerHub URL: ${{ fromJSON(steps.release.outputs.manifest).image_url }}'
          echo 'GitHub Commit URL: ${{ fromJSON(steps.release.outputs.manifest).commit_url }}'
