name: CI (Web)
on:
  push:
    paths:
      - ".github/workflows/ci-web.yml"
      - ".cargo/**"
      - "Cargo.*"
      - "**/*.rs"
      - "rust-toolchain"
      - "rustfmt.toml"
      - "ci/**"
      - "deploy/**"
      - "app/web/**"
jobs:

  ci-web:
    runs-on: self-hosted
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Login Docker
        id: login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9 # pin@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Execute CI target
        run: ( source /data/runners/.profile; cd ci; make ci-web )
        env:
          HONEYCOMB_TOKEN: ${{ secrets.HONEYCOMB_TOKEN }}
