name: Dev Environment Setup

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  setup-dev-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        run: |
          curl -L https://nixos.org/nix/install | sh -s -- --daemon
          source ~/.bashrc

      - name: Run nix develop
        run: |
          nix develop

      - name: Launch development environment
        run: |
          DEV_HOST=0.0.0.0 TILT_HOST=0.0.0.0 buck2 run dev:up