name: promote-pinga

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/promote-image.yml
      - .github/workflows/promote-pinga.yml
      - .cargo/**
      - Cargo.*
      - bin/pinga/**
      - lib/config-file/**
      - lib/dal/**
      - lib/sdf/**
      - lib/si-data/**
      - lib/si-settings/**
      - lib/telemetry-rs/**
      - rust-toolchain
      - rustfmt.toml

jobs:
  promote:
    uses: ./.github/workflows/promote-image.yml
    with:
      component_name: pinga
    secrets:
      SLACKBOT_TOKEN: ${{ secrets.SLACKBOT_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
