name: Try Build

on:
  issue_comment:
    types: [created, edited, deleted]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  try:
    if: ${{  github.event.issue.pull_request && startsWith(github.event.comment.body, '/try') }}
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-or-update-comment@v4
        id: init-comment
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Okay, starting a try! I\'ll update this comment once it\'s running...

      - uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch

      - uses: "buildkite/trigger-pipeline-action@v2.1.0"
        id: run-build
        with:
          buildkite_api_access_token: ${{ secrets.BUILDKITE_TOKEN }} # TODO(johnrwatson): This is Scott's Token at the minute, needs rotated
          pipeline: "system-initiative/si-merge-queue"
          branch: ${{ steps.comment-branch.outputs.head_ref }}
          message:  ":github: Try for branch ${{ steps.comment-branch.outputs.head_ref }}"
          ignore_pipeline_branch_filter: true
          send_pull_request: true

      - uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ steps.init-comment.outputs.comment-id }}
          body: |
            🚀 [Try running here](${{ steps.run-build.outputs.url }})! 🚀
