load("@prelude-si//:macros.bzl", "rust_library")

rust_library(
    name = "si-cbor",
    deps = [
        "//third-party/rust:ciborium",
        "//third-party/rust:remain",
        "//third-party/rust:serde",
        "//third-party/rust:thiserror",
    ],
    srcs = glob(["src/**/*.rs"]),
)
