load("@prelude-si//:macros.bzl", "rust_library", "rust_test")

rust_library(
    name = "test_lib",
    srcs = ["src/lib.rs"],
    deps = [],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "test_lib_test",
    srcs = ["src/lib.rs"],
    deps = [],
)
